ALTER TABLE cards_info
ADD COLUMN IF NOT EXISTS funding_source TEXT,
ADD COLUMN IF NOT EXISTS card_iin_type TEXT,
ADD COLUMN IF NOT EXISTS virtual_card BOOLEAN,
ADD COLUMN IF NOT EXISTS gambling_blocked BOOLEAN,
ADD COLUMN IF NOT EXISTS co_badged_card_networks TEXT[];
