# coding: utf-8

"""
    Hyperswitch - API Documentation

     ## Get started  Hyperswitch provides a collection of APIs that enable you to process and manage payments. Our APIs accept and return JSON in the HTTP body, and return standard HTTP response codes.  You can consume the APIs directly using your favorite HTTP/REST library.  We have a testing environment referred to \"sandbox\", which you can setup to test API calls without affecting production data. Currently, our sandbox environment is live while our production environment is under development and will be available soon. You can sign up on our Dashboard to get API keys to access Hyperswitch API.  ### Environment  Use the following base URLs when making requests to the APIs:  | Environment   |  Base URL                          | |---------------|------------------------------------| | Sandbox       | <https://sandbox.hyperswitch.io>   | | Production    | <https://api.hyperswitch.io>       |  ## Authentication  When you sign up on our [dashboard](https://app.hyperswitch.io) and create a merchant account, you are given a secret key (also referred as api-key) and a publishable key. You may authenticate all API requests with Hyperswitch server by providing the appropriate key in the request Authorization header.  | Key             |  Description                                                                                  | |-----------------|-----------------------------------------------------------------------------------------------| | api-key         | Private key. Used to authenticate all API requests from your merchant server                  | | publishable key | Unique identifier for your account. Used to authenticate API requests from your app's client  |  Never share your secret api keys. Keep them guarded and secure. 

    The version of the OpenAPI document: 0.1.0
    Contact: hyperswitch@juspay.in
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from hyperswitch.models.session_token import SessionToken

class TestSessionToken(unittest.TestCase):
    """SessionToken unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SessionToken:
        """Test SessionToken
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SessionToken`
        """
        model = SessionToken()
        if include_optional:
            return SessionToken(
                delayed_session_token = True,
                connector = '',
                sdk_next_action = hyperswitch.models.sdk_next_action.SdkNextAction(
                    next_action = 'post_session_tokens', ),
                merchant_info = hyperswitch.models.gpay_merchant_info.GpayMerchantInfo(
                    merchant_id = '', 
                    merchant_name = '', ),
                shipping_address_required = True,
                email_required = True,
                shipping_address_parameters = hyperswitch.models.gpay_shipping_address_parameters.GpayShippingAddressParameters(
                    phone_number_required = True, ),
                allowed_payment_methods = [
                    hyperswitch.models.gpay_allowed_payment_methods.GpayAllowedPaymentMethods(
                        type = '', 
                        parameters = hyperswitch.models.gpay_allowed_methods_parameters.GpayAllowedMethodsParameters(
                            allowed_auth_methods = [
                                ''
                                ], 
                            allowed_card_networks = [
                                ''
                                ], 
                            billing_address_required = True, 
                            billing_address_parameters = null, 
                            assurance_details_required = True, ), 
                        tokenization_specification = hyperswitch.models.gpay_tokenization_specification.GpayTokenizationSpecification(
                            type = '', 
                            parameters = hyperswitch.models.gpay_token_parameters.GpayTokenParameters(
                                gateway = '', 
                                gateway_merchant_id = '', 
                                stripe:version = '', 
                                stripe:publishable_key = '', 
                                protocol_version = '', 
                                public_key = '', ), ), )
                    ],
                transaction_info = hyperswitch.models.gpay_transaction_info.GpayTransactionInfo(
                    country_code = 'AF', 
                    currency_code = 'AED', 
                    total_price_status = '', 
                    total_price = '38.02', ),
                secrets = hyperswitch.models.secret_info_to_initiate_sdk.SecretInfoToInitiateSdk(
                    display = '', 
                    payment = '', ),
                wallet_name = 'no_session_token_received',
                version = '',
                service_id = '',
                order_number = '',
                merchant = hyperswitch.models.samsung_pay_merchant_payment_information.SamsungPayMerchantPaymentInformation(
                    name = '', 
                    url = '', 
                    country_code = 'AF', ),
                amount = hyperswitch.models.samsung_pay_amount_details.SamsungPayAmountDetails(
                    option = 'FORMAT_TOTAL_PRICE_ONLY', 
                    currency_code = 'AED', 
                    total = '38.02', ),
                protocol = 'PROTOCOL3DS',
                allowed_brands = [
                    ''
                    ],
                billing_address_required = True,
                session_token = '',
                session_id = '',
                session_token_data = None,
                payment_request_data = hyperswitch.models.apple_pay_payment_request.ApplePayPaymentRequest(
                    country_code = 'AF', 
                    currency_code = 'AED', 
                    total = hyperswitch.models.amount_info.AmountInfo(
                        label = '', 
                        type = '', 
                        amount = '38.02', ), 
                    merchant_capabilities = [
                        ''
                        ], 
                    supported_networks = [
                        ''
                        ], 
                    merchant_identifier = '', 
                    required_billing_contact_fields = null, 
                    required_shipping_contact_fields = null, 
                    recurring_payment_request = null, ),
                connector_reference_id = '',
                connector_sdk_public_key = '',
                connector_merchant_id = '',
                open_banking_session_token = '',
                client_id = '',
                client_name = '',
                client_profile_id = '',
                transaction_currency_code = 'AED',
                transaction_amount = '38.02',
                email_address = 'johntest@test.com',
                dpa_id = '',
                dpa_name = '',
                locale = '',
                card_brands = [
                    ''
                    ],
                acquirer_bin = '',
                acquirer_merchant_id = '',
                merchant_category_code = '',
                merchant_country_code = '',
                phone_number = '9123456789',
                email = 'johntest@test.com',
                phone_country_code = '',
                provider = 'visa',
                dpa_client_id = ''
            )
        else:
            return SessionToken(
                delayed_session_token = True,
                connector = '',
                sdk_next_action = hyperswitch.models.sdk_next_action.SdkNextAction(
                    next_action = 'post_session_tokens', ),
                merchant_info = hyperswitch.models.gpay_merchant_info.GpayMerchantInfo(
                    merchant_id = '', 
                    merchant_name = '', ),
                shipping_address_required = True,
                email_required = True,
                shipping_address_parameters = hyperswitch.models.gpay_shipping_address_parameters.GpayShippingAddressParameters(
                    phone_number_required = True, ),
                allowed_payment_methods = [
                    hyperswitch.models.gpay_allowed_payment_methods.GpayAllowedPaymentMethods(
                        type = '', 
                        parameters = hyperswitch.models.gpay_allowed_methods_parameters.GpayAllowedMethodsParameters(
                            allowed_auth_methods = [
                                ''
                                ], 
                            allowed_card_networks = [
                                ''
                                ], 
                            billing_address_required = True, 
                            billing_address_parameters = null, 
                            assurance_details_required = True, ), 
                        tokenization_specification = hyperswitch.models.gpay_tokenization_specification.GpayTokenizationSpecification(
                            type = '', 
                            parameters = hyperswitch.models.gpay_token_parameters.GpayTokenParameters(
                                gateway = '', 
                                gateway_merchant_id = '', 
                                stripe:version = '', 
                                stripe:publishable_key = '', 
                                protocol_version = '', 
                                public_key = '', ), ), )
                    ],
                transaction_info = hyperswitch.models.gpay_transaction_info.GpayTransactionInfo(
                    country_code = 'AF', 
                    currency_code = 'AED', 
                    total_price_status = '', 
                    total_price = '38.02', ),
                wallet_name = 'no_session_token_received',
                version = '',
                service_id = '',
                order_number = '',
                merchant = hyperswitch.models.samsung_pay_merchant_payment_information.SamsungPayMerchantPaymentInformation(
                    name = '', 
                    url = '', 
                    country_code = 'AF', ),
                amount = hyperswitch.models.samsung_pay_amount_details.SamsungPayAmountDetails(
                    option = 'FORMAT_TOTAL_PRICE_ONLY', 
                    currency_code = 'AED', 
                    total = '38.02', ),
                protocol = 'PROTOCOL3DS',
                allowed_brands = [
                    ''
                    ],
                billing_address_required = True,
                session_token = '',
                session_id = '',
                open_banking_session_token = '',
                client_id = '',
                client_name = '',
                client_profile_id = '',
                transaction_currency_code = 'AED',
                transaction_amount = '38.02',
                dpa_id = '',
                dpa_name = '',
                locale = '',
                card_brands = [
                    ''
                    ],
                acquirer_bin = '',
                acquirer_merchant_id = '',
                merchant_category_code = '',
                merchant_country_code = '',
        )
        """

    def testSessionToken(self):
        """Test SessionToken"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
