# coding: utf-8

"""
    Hyperswitch - API Documentation

     ## Get started  Hyperswitch provides a collection of APIs that enable you to process and manage payments. Our APIs accept and return JSON in the HTTP body, and return standard HTTP response codes.  You can consume the APIs directly using your favorite HTTP/REST library.  We have a testing environment referred to \"sandbox\", which you can setup to test API calls without affecting production data. Currently, our sandbox environment is live while our production environment is under development and will be available soon. You can sign up on our Dashboard to get API keys to access Hyperswitch API.  ### Environment  Use the following base URLs when making requests to the APIs:  | Environment   |  Base URL                          | |---------------|------------------------------------| | Sandbox       | <https://sandbox.hyperswitch.io>   | | Production    | <https://api.hyperswitch.io>       |  ## Authentication  When you sign up on our [dashboard](https://app.hyperswitch.io) and create a merchant account, you are given a secret key (also referred as api-key) and a publishable key. You may authenticate all API requests with Hyperswitch server by providing the appropriate key in the request Authorization header.  | Key             |  Description                                                                                  | |-----------------|-----------------------------------------------------------------------------------------------| | api-key         | Private key. Used to authenticate all API requests from your merchant server                  | | publishable key | Unique identifier for your account. Used to authenticate API requests from your app's client  |  Never share your secret api keys. Keep them guarded and secure. 

    The version of the OpenAPI document: 0.1.0
    Contact: hyperswitch@juspay.in
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from hyperswitch.api.blocklist_api import BlocklistApi


class TestBlocklistApi(unittest.TestCase):
    """BlocklistApi unit test stubs"""

    def setUp(self) -> None:
        self.api = BlocklistApi()

    def tearDown(self) -> None:
        pass

    def test_block_a_fingerprint(self) -> None:
        """Test case for block_a_fingerprint

        """
        pass

    def test_list_blocked_fingerprints_of_a_particular_kind(self) -> None:
        """Test case for list_blocked_fingerprints_of_a_particular_kind

        """
        pass

    def test_toggle_blocklist_guard_for_a_particular_merchant(self) -> None:
        """Test case for toggle_blocklist_guard_for_a_particular_merchant

        """
        pass

    def test_unblock_a_fingerprint(self) -> None:
        """Test case for unblock_a_fingerprint

        """
        pass


if __name__ == '__main__':
    unittest.main()
