-- Your SQL goes here
ALTER TYPE "Currency" ADD VALUE IF NOT EXISTS 'CLF' AFTER 'CHF';

ALTER TYPE "Currency" ADD VALUE IF NOT EXISTS 'CUC' AFTER 'CRC';

ALTER TYPE "Currency" ADD VALUE IF NOT EXISTS 'STD' AFTER 'SSP';
