use router_derive;
use serde::{Deserialize, Serialize};

#[derive(
    Clone,
    Debug,
    Eq,
    Default,
    Hash,
    PartialEq,
    serde::Deserialize,
    serde::Serialize,
    strum::Display,
    strum::EnumString,
    utoipa::ToSchema,
    Copy
)]
#[router_derive::diesel_enum(storage_type = "pg_enum")]
#[rustfmt::skip]
pub enum CountryCode {
    AF, AX, AL, DZ, AS, AD, AO, AI, AQ, AG, AR, AM, AW, AU, AT,
    AZ, BS, BH, BD, BB, BY, BE, BZ, BJ, BM, BT, BO, BQ, BA, BW,
    BV, BR, IO, BN, BG, BF, BI, KH, CM, CA, CV, KY, CF, TD, CL,
    CN, CX, CC, CO, KM, CG, CD, CK, CR, CI, HR, CU, CW, CY, CZ,
    DK, DJ, DM, DO, EC, EG, SV, GQ, ER, EE, ET, FK, FO, FJ, FI,
    FR, GF, PF, TF, GA, GM, GE, DE, GH, GI, GR, GL, GD, GP, GU,
    GT, GG, GN, GW, GY, HT, HM, VA, HN, HK, HU, IS, IN, ID, IR,
    IQ, IE, IM, IL, IT, JM, JP, JE, JO, KZ, KE, KI, KP, KR, KW,
    KG, LA, LV, LB, LS, LR, LY, LI, LT, LU, MO, MK, MG, MW, MY,
    MV, ML, MT, MH, MQ, MR, MU, YT, MX, FM, MD, MC, MN, ME, MS,
    MA, MZ, MM, NA, NR, NP, NL, NC, NZ, NI, NE, NG, NU, NF, MP,
    NO, OM, PK, PW, PS, PA, PG, PY, PE, PH, PN, PL, PT, PR, QA,
    RE, RO, RU, RW, BL, SH, KN, LC, MF, PM, VC, WS, SM, ST, SA,
    SN, RS, SC, SL, SG, SX, SK, SI, SB, SO, ZA, GS, SS, ES, LK,
    SD, SR, SJ, SZ, SE, CH, SY, TW, TJ, TZ, TH, TL, TG, TK, TO,
    TT, TN, TR, TM, TC, TV, UG, UA, AE, GB, UM, UY, UZ, VU,
    VE, VN, VG, VI, WF, EH, YE, ZM, ZW,
    #[default]
    US
}

#[derive(Clone, Copy, Debug, Serialize, Deserialize)]
pub enum CountryAlpha2 {
    AF, AX, AL, DZ, AS, AD, AO, AI, AQ, AG, AR, AM, AW, AU, AT, AZ, BS, BH, BD, BB, BY, BE, BZ, BJ,
    BM, BT, BO, BQ, BA, BW, BV, BR, IO, BN, BG, BF, BI, CV, KH, CM, CA, KY, CF, TD, CL, CN, CX, CC,
    CO, KM, CG, CD, CK, CR, CI, HR, CU, CW, CY, CZ, DK, DJ, DM, DO, EC, EG, SV, GQ, ER, EE, ET, FK,
    FO, FJ, FI, FR, GF, PF, TF, GA, GM, GE, DE, GH, GI, GR, GL, GD, GP, GU, GT, GG, GN, GW, GY, HT,
    HM, VA, HN, HK, HU, IS, IN, ID, IR, IQ, IE, IM, IL, IT, JM, JP, JE, JO, KZ, KE, KI, KP, KR, KW,
    KG, LA, LV, LB, LS, LR, LY, LI, LT, LU, MO, MK, MG, MW, MY, MV, ML, MT, MH, MQ, MR, MU, YT, MX,
    FM, MD, MC, MN, ME, MS, MA, MZ, MM, NA, NR, NP, NL, NC, NZ, NI, NE, NG, NU, NF, MP, NO, OM, PK,
    PW, PS, PA, PG, PY, PE, PH, PN, PL, PT, PR, QA, RE, RO, RU, RW, BL, SH, KN, LC, MF, PM, VC, WS,
    SM, ST, SA, SN, RS, SC, SL, SG, SX, SK, SI, SB, SO, ZA, GS, SS, ES, LK, SD, SR, SJ, SZ, SE, CH,
    SY, TW, TJ, TZ, TH, TL, TG, TK, TO, TT, TN, TR, TM, TC, TV, UG, UA, AE, GB, US, UM, UY, UZ, VU,
    VE, VN, VG, VI, WF, EH, YE, ZM, ZW,
}
#[derive(Clone, Copy, Debug, Serialize, Deserialize)]
pub enum CountryAlpha3 {
    AFG, ALA, ALB, DZA, ASM, AND, AGO, AIA, ATA, ATG, ARG, ARM, ABW, AUS, AUT, AZE, BHS, BHR, BGD,
    BRB, BLR, BEL, BLZ, BEN, BMU, BTN, BOL, BES, BIH, BWA, BVT, BRA, IOT, BRN, BGR, BFA, BDI, CPV,
    KHM, CMR, CAN, CYM, CAF, TCD, CHL, CHN, CXR, CCK, COL, COM, COG, COD, COK, CRI, CIV, HRV, CUB,
    CUW, CYP, CZE, DNK, DJI, DMA, DOM, ECU, EGY, SLV, GNQ, ERI, EST, ETH, FLK, FRO, FJI, FIN, FRA,
    GUF, PYF, ATF, GAB, GMB, GEO, DEU, GHA, GIB, GRC, GRL, GRD, GLP, GUM, GTM, GGY, GIN, GNB, GUY,
    HTI, HMD, VAT, HND, HKG, HUN, ISL, IND, IDN, IRN, IRQ, IRL, IMN, ISR, ITA, JAM, JPN, JEY, JOR,
    KAZ, KEN, KIR, PRK, KOR, KWT, KGZ, LAO, LVA, LBN, LSO, LBR, LBY, LIE, LTU, LUX, MAC, MKD, MDG,
    MWI, MYS, MDV, MLI, MLT, MHL, MTQ, MRT, MUS, MYT, MEX, FSM, MDA, MCO, MNG, MNE, MSR, MAR, MOZ,
    MMR, NAM, NRU, NPL, NLD, NCL, NZL, NIC, NER, NGA, NIU, NFK, MNP, NOR, OMN, PAK, PLW, PSE, PAN,
    PNG, PRY, PER, PHL, PCN, POL, PRT, PRI, QAT, REU, ROU, RUS, RWA, BLM, SHN, KNA, LCA, MAF, SPM,
    VCT, WSM, SMR, STP, SAU, SEN, SRB, SYC, SLE, SGP, SXM, SVK, SVN, SLB, SOM, ZAF, SGS, SSD, ESP,
    LKA, SDN, SUR, SJM, SWZ, SWE, CHE, SYR, TWN, TJK, TZA, THA, TLS, TGO, TKL, TON, TTO, TUN, TUR,
    TKM, TCA, TUV, UGA, UKR, ARE, GBR, USA, UMI, URY, UZB, VUT, VEN, VNM, VGB, VIR, WLF, ESH, YEM,
    ZMB, ZWE,
}

#[derive(Clone, Copy, Debug, PartialEq)]
pub enum Country {
    Afghanistan,
    ÅlandIslands,
    Albania,
    Algeria,
    AmericanSamoa,
    Andorra,
    Angola,
    Anguilla,
    Antarctica,
    AntiguaandBarbuda,
    Argentina,
    Armenia,
    Aruba,
    Australia,
    Austria,
    Azerbaijan,
    Bahamas,
    Bahrain,
    Bangladesh,
    Barbados,
    Belarus,
    Belgium,
    Belize,
    Benin,
    Bermuda,
    Bhutan,
    BoliviaPlurinationalStateof,
    BonaireSintEustatiusandSaba,
    BosniaandHerzegovina,
    Botswana,
    BouvetIsland,
    Brazil,
    BritishIndianOceanTerritory,
    BruneiDarussalam,
    Bulgaria,
    BurkinaFaso,
    Burundi,
    CaboVerde,
    Cambodia,
    Cameroon,
    Canada,
    CaymanIslands,
    CentralAfricanRepublic,
    Chad,
    Chile,
    China,
    ChristmasIsland,
    CocosKeelingIslands,
    Colombia,
    Comoros,
    Congo,
    CongoDemocraticRepublicofthe,
    CookIslands,
    CostaRica,
    CôtedIvoire,
    Croatia,
    Cuba,
    Curaçao,
    Cyprus,
    Czechia,
    Denmark,
    Djibouti,
    Dominica,
    DominicanRepublic,
    Ecuador,
    Egypt,
    ElSalvador,
    EquatorialGuinea,
    Eritrea,
    Estonia,
    Ethiopia,
    FalklandIslandsMalvinas,
    FaroeIslands,
    Fiji,
    Finland,
    France,
    FrenchGuiana,
    FrenchPolynesia,
    FrenchSouthernTerritories,
    Gabon,
    Gambia,
    Georgia,
    Germany,
    Ghana,
    Gibraltar,
    Greece,
    Greenland,
    Grenada,
    Guadeloupe,
    Guam,
    Guatemala,
    Guernsey,
    Guinea,
    GuineaBissau,
    Guyana,
    Haiti,
    HeardIslandandMcDonaldIslands,
    HolySee,
    Honduras,
    HongKong,
    Hungary,
    Iceland,
    India,
    Indonesia,
    IranIslamicRepublicof,
    Iraq,
    Ireland,
    IsleofMan,
    Israel,
    Italy,
    Jamaica,
    Japan,
    Jersey,
    Jordan,
    Kazakhstan,
    Kenya,
    Kiribati,
    KoreaDemocraticPeoplesRepublicof,
    KoreaRepublicof,
    Kuwait,
    Kyrgyzstan,
    LaoPeoplesDemocraticRepublic,
    Latvia,
    Lebanon,
    Lesotho,
    Liberia,
    Libya,
    Liechtenstein,
    Lithuania,
    Luxembourg,
    Macao,
    MacedoniatheformerYugoslavRepublicof,
    Madagascar,
    Malawi,
    Malaysia,
    Maldives,
    Mali,
    Malta,
    MarshallIslands,
    Martinique,
    Mauritania,
    Mauritius,
    Mayotte,
    Mexico,
    MicronesiaFederatedStatesof,
    MoldovaRepublicof,
    Monaco,
    Mongolia,
    Montenegro,
    Montserrat,
    Morocco,
    Mozambique,
    Myanmar,
    Namibia,
    Nauru,
    Nepal,
    Netherlands,
    NewCaledonia,
    NewZealand,
    Nicaragua,
    Niger,
    Nigeria,
    Niue,
    NorfolkIsland,
    NorthernMarianaIslands,
    Norway,
    Oman,
    Pakistan,
    Palau,
    PalestineStateof,
    Panama,
    PapuaNewGuinea,
    Paraguay,
    Peru,
    Philippines,
    Pitcairn,
    Poland,
    Portugal,
    PuertoRico,
    Qatar,
    Réunion,
    Romania,
    RussianFederation,
    Rwanda,
    SaintBarthélemy,
    SaintHelenaAscensionandTristandaCunha,
    SaintKittsandNevis,
    SaintLucia,
    SaintMartinFrenchpart,
    SaintPierreandMiquelon,
    SaintVincentandtheGrenadines,
    Samoa,
    SanMarino,
    SaoTomeandPrincipe,
    SaudiArabia,
    Senegal,
    Serbia,
    Seychelles,
    SierraLeone,
    Singapore,
    SintMaartenDutchpart,
    Slovakia,
    Slovenia,
    SolomonIslands,
    Somalia,
    SouthAfrica,
    SouthGeorgiaandtheSouthSandwichIslands,
    SouthSudan,
    Spain,
    SriLanka,
    Sudan,
    Suriname,
    SvalbardandJanMayen,
    Swaziland,
    Sweden,
    Switzerland,
    SyrianArabRepublic,
    TaiwanProvinceofChina,
    Tajikistan,
    TanzaniaUnitedRepublicof,
    Thailand,
    TimorLeste,
    Togo,
    Tokelau,
    Tonga,
    TrinidadandTobago,
    Tunisia,
    Turkey,
    Turkmenistan,
    TurksandCaicosIslands,
    Tuvalu,
    Uganda,
    Ukraine,
    UnitedArabEmirates,
    UnitedKingdomofGreatBritainandNorthernIreland,
    UnitedStatesofAmerica,
    UnitedStatesMinorOutlyingIslands,
    Uruguay,
    Uzbekistan,
    Vanuatu,
    VenezuelaBolivarianRepublicof,
    VietNam,
    VirginIslandsBritish,
    VirginIslandsUS,
    WallisandFutuna,
    WesternSahara,
    Yemen,
    Zambia,
    Zimbabwe,
}

impl Country {
    pub const fn from_alpha2(code: CountryAlpha2) -> Self {
        match code {
            CountryAlpha2::AF => Self::Afghanistan,
            CountryAlpha2::AX => Self::ÅlandIslands,
            CountryAlpha2::AL => Self::Albania,
            CountryAlpha2::DZ => Self::Algeria,
            CountryAlpha2::AS => Self::AmericanSamoa,
            CountryAlpha2::AD => Self::Andorra,
            CountryAlpha2::AO => Self::Angola,
            CountryAlpha2::AI => Self::Anguilla,
            CountryAlpha2::AQ => Self::Antarctica,
            CountryAlpha2::AG => Self::AntiguaandBarbuda,
            CountryAlpha2::AR => Self::Argentina,
            CountryAlpha2::AM => Self::Armenia,
            CountryAlpha2::AW => Self::Aruba,
            CountryAlpha2::AU => Self::Australia,
            CountryAlpha2::AT => Self::Austria,
            CountryAlpha2::AZ => Self::Azerbaijan,
            CountryAlpha2::BS => Self::Bahamas,
            CountryAlpha2::BH => Self::Bahrain,
            CountryAlpha2::BD => Self::Bangladesh,
            CountryAlpha2::BB => Self::Barbados,
            CountryAlpha2::BY => Self::Belarus,
            CountryAlpha2::BE => Self::Belgium,
            CountryAlpha2::BZ => Self::Belize,
            CountryAlpha2::BJ => Self::Benin,
            CountryAlpha2::BM => Self::Bermuda,
            CountryAlpha2::BT => Self::Bhutan,
            CountryAlpha2::BO => Self::BoliviaPlurinationalStateof,
            CountryAlpha2::BQ => Self::BonaireSintEustatiusandSaba,
            CountryAlpha2::BA => Self::BosniaandHerzegovina,
            CountryAlpha2::BW => Self::Botswana,
            CountryAlpha2::BV => Self::BouvetIsland,
            CountryAlpha2::BR => Self::Brazil,
            CountryAlpha2::IO => Self::BritishIndianOceanTerritory,
            CountryAlpha2::BN => Self::BruneiDarussalam,
            CountryAlpha2::BG => Self::Bulgaria,
            CountryAlpha2::BF => Self::BurkinaFaso,
            CountryAlpha2::BI => Self::Burundi,
            CountryAlpha2::CV => Self::CaboVerde,
            CountryAlpha2::KH => Self::Cambodia,
            CountryAlpha2::CM => Self::Cameroon,
            CountryAlpha2::CA => Self::Canada,
            CountryAlpha2::KY => Self::CaymanIslands,
            CountryAlpha2::CF => Self::CentralAfricanRepublic,
            CountryAlpha2::TD => Self::Chad,
            CountryAlpha2::CL => Self::Chile,
            CountryAlpha2::CN => Self::China,
            CountryAlpha2::CX => Self::ChristmasIsland,
            CountryAlpha2::CC => Self::CocosKeelingIslands,
            CountryAlpha2::CO => Self::Colombia,
            CountryAlpha2::KM => Self::Comoros,
            CountryAlpha2::CG => Self::Congo,
            CountryAlpha2::CD => Self::CongoDemocraticRepublicofthe,
            CountryAlpha2::CK => Self::CookIslands,
            CountryAlpha2::CR => Self::CostaRica,
            CountryAlpha2::CI => Self::CôtedIvoire,
            CountryAlpha2::HR => Self::Croatia,
            CountryAlpha2::CU => Self::Cuba,
            CountryAlpha2::CW => Self::Curaçao,
            CountryAlpha2::CY => Self::Cyprus,
            CountryAlpha2::CZ => Self::Czechia,
            CountryAlpha2::DK => Self::Denmark,
            CountryAlpha2::DJ => Self::Djibouti,
            CountryAlpha2::DM => Self::Dominica,
            CountryAlpha2::DO => Self::DominicanRepublic,
            CountryAlpha2::EC => Self::Ecuador,
            CountryAlpha2::EG => Self::Egypt,
            CountryAlpha2::SV => Self::ElSalvador,
            CountryAlpha2::GQ => Self::EquatorialGuinea,
            CountryAlpha2::ER => Self::Eritrea,
            CountryAlpha2::EE => Self::Estonia,
            CountryAlpha2::ET => Self::Ethiopia,
            CountryAlpha2::FK => Self::FalklandIslandsMalvinas,
            CountryAlpha2::FO => Self::FaroeIslands,
            CountryAlpha2::FJ => Self::Fiji,
            CountryAlpha2::FI => Self::Finland,
            CountryAlpha2::FR => Self::France,
            CountryAlpha2::GF => Self::FrenchGuiana,
            CountryAlpha2::PF => Self::FrenchPolynesia,
            CountryAlpha2::TF => Self::FrenchSouthernTerritories,
            CountryAlpha2::GA => Self::Gabon,
            CountryAlpha2::GM => Self::Gambia,
            CountryAlpha2::GE => Self::Georgia,
            CountryAlpha2::DE => Self::Germany,
            CountryAlpha2::GH => Self::Ghana,
            CountryAlpha2::GI => Self::Gibraltar,
            CountryAlpha2::GR => Self::Greece,
            CountryAlpha2::GL => Self::Greenland,
            CountryAlpha2::GD => Self::Grenada,
            CountryAlpha2::GP => Self::Guadeloupe,
            CountryAlpha2::GU => Self::Guam,
            CountryAlpha2::GT => Self::Guatemala,
            CountryAlpha2::GG => Self::Guernsey,
            CountryAlpha2::GN => Self::Guinea,
            CountryAlpha2::GW => Self::GuineaBissau,
            CountryAlpha2::GY => Self::Guyana,
            CountryAlpha2::HT => Self::Haiti,
            CountryAlpha2::HM => Self::HeardIslandandMcDonaldIslands,
            CountryAlpha2::VA => Self::HolySee,
            CountryAlpha2::HN => Self::Honduras,
            CountryAlpha2::HK => Self::HongKong,
            CountryAlpha2::HU => Self::Hungary,
            CountryAlpha2::IS => Self::Iceland,
            CountryAlpha2::IN => Self::India,
            CountryAlpha2::ID => Self::Indonesia,
            CountryAlpha2::IR => Self::IranIslamicRepublicof,
            CountryAlpha2::IQ => Self::Iraq,
            CountryAlpha2::IE => Self::Ireland,
            CountryAlpha2::IM => Self::IsleofMan,
            CountryAlpha2::IL => Self::Israel,
            CountryAlpha2::IT => Self::Italy,
            CountryAlpha2::JM => Self::Jamaica,
            CountryAlpha2::JP => Self::Japan,
            CountryAlpha2::JE => Self::Jersey,
            CountryAlpha2::JO => Self::Jordan,
            CountryAlpha2::KZ => Self::Kazakhstan,
            CountryAlpha2::KE => Self::Kenya,
            CountryAlpha2::KI => Self::Kiribati,
            CountryAlpha2::KP => Self::KoreaDemocraticPeoplesRepublicof,
            CountryAlpha2::KR => Self::KoreaRepublicof,
            CountryAlpha2::KW => Self::Kuwait,
            CountryAlpha2::KG => Self::Kyrgyzstan,
            CountryAlpha2::LA => Self::LaoPeoplesDemocraticRepublic,
            CountryAlpha2::LV => Self::Latvia,
            CountryAlpha2::LB => Self::Lebanon,
            CountryAlpha2::LS => Self::Lesotho,
            CountryAlpha2::LR => Self::Liberia,
            CountryAlpha2::LY => Self::Libya,
            CountryAlpha2::LI => Self::Liechtenstein,
            CountryAlpha2::LT => Self::Lithuania,
            CountryAlpha2::LU => Self::Luxembourg,
            CountryAlpha2::MO => Self::Macao,
            CountryAlpha2::MK => Self::MacedoniatheformerYugoslavRepublicof,
            CountryAlpha2::MG => Self::Madagascar,
            CountryAlpha2::MW => Self::Malawi,
            CountryAlpha2::MY => Self::Malaysia,
            CountryAlpha2::MV => Self::Maldives,
            CountryAlpha2::ML => Self::Mali,
            CountryAlpha2::MT => Self::Malta,
            CountryAlpha2::MH => Self::MarshallIslands,
            CountryAlpha2::MQ => Self::Martinique,
            CountryAlpha2::MR => Self::Mauritania,
            CountryAlpha2::MU => Self::Mauritius,
            CountryAlpha2::YT => Self::Mayotte,
            CountryAlpha2::MX => Self::Mexico,
            CountryAlpha2::FM => Self::MicronesiaFederatedStatesof,
            CountryAlpha2::MD => Self::MoldovaRepublicof,
            CountryAlpha2::MC => Self::Monaco,
            CountryAlpha2::MN => Self::Mongolia,
            CountryAlpha2::ME => Self::Montenegro,
            CountryAlpha2::MS => Self::Montserrat,
            CountryAlpha2::MA => Self::Morocco,
            CountryAlpha2::MZ => Self::Mozambique,
            CountryAlpha2::MM => Self::Myanmar,
            CountryAlpha2::NA => Self::Namibia,
            CountryAlpha2::NR => Self::Nauru,
            CountryAlpha2::NP => Self::Nepal,
            CountryAlpha2::NL => Self::Netherlands,
            CountryAlpha2::NC => Self::NewCaledonia,
            CountryAlpha2::NZ => Self::NewZealand,
            CountryAlpha2::NI => Self::Nicaragua,
            CountryAlpha2::NE => Self::Niger,
            CountryAlpha2::NG => Self::Nigeria,
            CountryAlpha2::NU => Self::Niue,
            CountryAlpha2::NF => Self::NorfolkIsland,
            CountryAlpha2::MP => Self::NorthernMarianaIslands,
            CountryAlpha2::NO => Self::Norway,
            CountryAlpha2::OM => Self::Oman,
            CountryAlpha2::PK => Self::Pakistan,
            CountryAlpha2::PW => Self::Palau,
            CountryAlpha2::PS => Self::PalestineStateof,
            CountryAlpha2::PA => Self::Panama,
            CountryAlpha2::PG => Self::PapuaNewGuinea,
            CountryAlpha2::PY => Self::Paraguay,
            CountryAlpha2::PE => Self::Peru,
            CountryAlpha2::PH => Self::Philippines,
            CountryAlpha2::PN => Self::Pitcairn,
            CountryAlpha2::PL => Self::Poland,
            CountryAlpha2::PT => Self::Portugal,
            CountryAlpha2::PR => Self::PuertoRico,
            CountryAlpha2::QA => Self::Qatar,
            CountryAlpha2::RE => Self::Réunion,
            CountryAlpha2::RO => Self::Romania,
            CountryAlpha2::RU => Self::RussianFederation,
            CountryAlpha2::RW => Self::Rwanda,
            CountryAlpha2::BL => Self::SaintBarthélemy,
            CountryAlpha2::SH => Self::SaintHelenaAscensionandTristandaCunha,
            CountryAlpha2::KN => Self::SaintKittsandNevis,
            CountryAlpha2::LC => Self::SaintLucia,
            CountryAlpha2::MF => Self::SaintMartinFrenchpart,
            CountryAlpha2::PM => Self::SaintPierreandMiquelon,
            CountryAlpha2::VC => Self::SaintVincentandtheGrenadines,
            CountryAlpha2::WS => Self::Samoa,
            CountryAlpha2::SM => Self::SanMarino,
            CountryAlpha2::ST => Self::SaoTomeandPrincipe,
            CountryAlpha2::SA => Self::SaudiArabia,
            CountryAlpha2::SN => Self::Senegal,
            CountryAlpha2::RS => Self::Serbia,
            CountryAlpha2::SC => Self::Seychelles,
            CountryAlpha2::SL => Self::SierraLeone,
            CountryAlpha2::SG => Self::Singapore,
            CountryAlpha2::SX => Self::SintMaartenDutchpart,
            CountryAlpha2::SK => Self::Slovakia,
            CountryAlpha2::SI => Self::Slovenia,
            CountryAlpha2::SB => Self::SolomonIslands,
            CountryAlpha2::SO => Self::Somalia,
            CountryAlpha2::ZA => Self::SouthAfrica,
            CountryAlpha2::GS => Self::SouthGeorgiaandtheSouthSandwichIslands,
            CountryAlpha2::SS => Self::SouthSudan,
            CountryAlpha2::ES => Self::Spain,
            CountryAlpha2::LK => Self::SriLanka,
            CountryAlpha2::SD => Self::Sudan,
            CountryAlpha2::SR => Self::Suriname,
            CountryAlpha2::SJ => Self::SvalbardandJanMayen,
            CountryAlpha2::SZ => Self::Swaziland,
            CountryAlpha2::SE => Self::Sweden,
            CountryAlpha2::CH => Self::Switzerland,
            CountryAlpha2::SY => Self::SyrianArabRepublic,
            CountryAlpha2::TW => Self::TaiwanProvinceofChina,
            CountryAlpha2::TJ => Self::Tajikistan,
            CountryAlpha2::TZ => Self::TanzaniaUnitedRepublicof,
            CountryAlpha2::TH => Self::Thailand,
            CountryAlpha2::TL => Self::TimorLeste,
            CountryAlpha2::TG => Self::Togo,
            CountryAlpha2::TK => Self::Tokelau,
            CountryAlpha2::TO => Self::Tonga,
            CountryAlpha2::TT => Self::TrinidadandTobago,
            CountryAlpha2::TN => Self::Tunisia,
            CountryAlpha2::TR => Self::Turkey,
            CountryAlpha2::TM => Self::Turkmenistan,
            CountryAlpha2::TC => Self::TurksandCaicosIslands,
            CountryAlpha2::TV => Self::Tuvalu,
            CountryAlpha2::UG => Self::Uganda,
            CountryAlpha2::UA => Self::Ukraine,
            CountryAlpha2::AE => Self::UnitedArabEmirates,
            CountryAlpha2::GB => Self::UnitedKingdomofGreatBritainandNorthernIreland,
            CountryAlpha2::US => Self::UnitedStatesofAmerica,
            CountryAlpha2::UM => Self::UnitedStatesMinorOutlyingIslands,
            CountryAlpha2::UY => Self::Uruguay,
            CountryAlpha2::UZ => Self::Uzbekistan,
            CountryAlpha2::VU => Self::Vanuatu,
            CountryAlpha2::VE => Self::VenezuelaBolivarianRepublicof,
            CountryAlpha2::VN => Self::VietNam,
            CountryAlpha2::VG => Self::VirginIslandsBritish,
            CountryAlpha2::VI => Self::VirginIslandsUS,
            CountryAlpha2::WF => Self::WallisandFutuna,
            CountryAlpha2::EH => Self::WesternSahara,
            CountryAlpha2::YE => Self::Yemen,
            CountryAlpha2::ZM => Self::Zambia,
            CountryAlpha2::ZW => Self::Zimbabwe,
        }
    }
    pub const fn to_alpha2(&self) -> CountryAlpha2 {
        match self {
            Country::Afghanistan => CountryAlpha2::AF,
            Country::ÅlandIslands => CountryAlpha2::AX,
            Country::Albania => CountryAlpha2::AL,
            Country::Algeria => CountryAlpha2::DZ,
            Country::AmericanSamoa => CountryAlpha2::AS,
            Country::Andorra => CountryAlpha2::AD,
            Country::Angola => CountryAlpha2::AO,
            Country::Anguilla => CountryAlpha2::AI,
            Country::Antarctica => CountryAlpha2::AQ,
            Country::AntiguaandBarbuda => CountryAlpha2::AG,
            Country::Argentina => CountryAlpha2::AR,
            Country::Armenia => CountryAlpha2::AM,
            Country::Aruba => CountryAlpha2::AW,
            Country::Australia => CountryAlpha2::AU,
            Country::Austria => CountryAlpha2::AT,
            Country::Azerbaijan => CountryAlpha2::AZ,
            Country::Bahamas => CountryAlpha2::BS,
            Country::Bahrain => CountryAlpha2::BH,
            Country::Bangladesh => CountryAlpha2::BD,
            Country::Barbados => CountryAlpha2::BB,
            Country::Belarus => CountryAlpha2::BY,
            Country::Belgium => CountryAlpha2::BE,
            Country::Belize => CountryAlpha2::BZ,
            Country::Benin => CountryAlpha2::BJ,
            Country::Bermuda => CountryAlpha2::BM,
            Country::Bhutan => CountryAlpha2::BT,
            Country::BoliviaPlurinationalStateof => CountryAlpha2::BO,
            Country::BonaireSintEustatiusandSaba => CountryAlpha2::BQ,
            Country::BosniaandHerzegovina => CountryAlpha2::BA,
            Country::Botswana => CountryAlpha2::BW,
            Country::BouvetIsland => CountryAlpha2::BV,
            Country::Brazil => CountryAlpha2::BR,
            Country::BritishIndianOceanTerritory => CountryAlpha2::IO,
            Country::BruneiDarussalam => CountryAlpha2::BN,
            Country::Bulgaria => CountryAlpha2::BG,
            Country::BurkinaFaso => CountryAlpha2::BF,
            Country::Burundi => CountryAlpha2::BI,
            Country::CaboVerde => CountryAlpha2::CV,
            Country::Cambodia => CountryAlpha2::KH,
            Country::Cameroon => CountryAlpha2::CM,
            Country::Canada => CountryAlpha2::CA,
            Country::CaymanIslands => CountryAlpha2::KY,
            Country::CentralAfricanRepublic => CountryAlpha2::CF,
            Country::Chad => CountryAlpha2::TD,
            Country::Chile => CountryAlpha2::CL,
            Country::China => CountryAlpha2::CN,
            Country::ChristmasIsland => CountryAlpha2::CX,
            Country::CocosKeelingIslands => CountryAlpha2::CC,
            Country::Colombia => CountryAlpha2::CO,
            Country::Comoros => CountryAlpha2::KM,
            Country::Congo => CountryAlpha2::CG,
            Country::CongoDemocraticRepublicofthe => CountryAlpha2::CD,
            Country::CookIslands => CountryAlpha2::CK,
            Country::CostaRica => CountryAlpha2::CR,
            Country::CôtedIvoire => CountryAlpha2::CI,
            Country::Croatia => CountryAlpha2::HR,
            Country::Cuba => CountryAlpha2::CU,
            Country::Curaçao => CountryAlpha2::CW,
            Country::Cyprus => CountryAlpha2::CY,
            Country::Czechia => CountryAlpha2::CZ,
            Country::Denmark => CountryAlpha2::DK,
            Country::Djibouti => CountryAlpha2::DJ,
            Country::Dominica => CountryAlpha2::DM,
            Country::DominicanRepublic => CountryAlpha2::DO,
            Country::Ecuador => CountryAlpha2::EC,
            Country::Egypt => CountryAlpha2::EG,
            Country::ElSalvador => CountryAlpha2::SV,
            Country::EquatorialGuinea => CountryAlpha2::GQ,
            Country::Eritrea => CountryAlpha2::ER,
            Country::Estonia => CountryAlpha2::EE,
            Country::Ethiopia => CountryAlpha2::ET,
            Country::FalklandIslandsMalvinas => CountryAlpha2::FK,
            Country::FaroeIslands => CountryAlpha2::FO,
            Country::Fiji => CountryAlpha2::FJ,
            Country::Finland => CountryAlpha2::FI,
            Country::France => CountryAlpha2::FR,
            Country::FrenchGuiana => CountryAlpha2::GF,
            Country::FrenchPolynesia => CountryAlpha2::PF,
            Country::FrenchSouthernTerritories => CountryAlpha2::TF,
            Country::Gabon => CountryAlpha2::GA,
            Country::Gambia => CountryAlpha2::GM,
            Country::Georgia => CountryAlpha2::GE,
            Country::Germany => CountryAlpha2::DE,
            Country::Ghana => CountryAlpha2::GH,
            Country::Gibraltar => CountryAlpha2::GI,
            Country::Greece => CountryAlpha2::GR,
            Country::Greenland => CountryAlpha2::GL,
            Country::Grenada => CountryAlpha2::GD,
            Country::Guadeloupe => CountryAlpha2::GP,
            Country::Guam => CountryAlpha2::GU,
            Country::Guatemala => CountryAlpha2::GT,
            Country::Guernsey => CountryAlpha2::GG,
            Country::Guinea => CountryAlpha2::GN,
            Country::GuineaBissau => CountryAlpha2::GW,
            Country::Guyana => CountryAlpha2::GY,
            Country::Haiti => CountryAlpha2::HT,
            Country::HeardIslandandMcDonaldIslands => CountryAlpha2::HM,
            Country::HolySee => CountryAlpha2::VA,
            Country::Honduras => CountryAlpha2::HN,
            Country::HongKong => CountryAlpha2::HK,
            Country::Hungary => CountryAlpha2::HU,
            Country::Iceland => CountryAlpha2::IS,
            Country::India => CountryAlpha2::IN,
            Country::Indonesia => CountryAlpha2::ID,
            Country::IranIslamicRepublicof => CountryAlpha2::IR,
            Country::Iraq => CountryAlpha2::IQ,
            Country::Ireland => CountryAlpha2::IE,
            Country::IsleofMan => CountryAlpha2::IM,
            Country::Israel => CountryAlpha2::IL,
            Country::Italy => CountryAlpha2::IT,
            Country::Jamaica => CountryAlpha2::JM,
            Country::Japan => CountryAlpha2::JP,
            Country::Jersey => CountryAlpha2::JE,
            Country::Jordan => CountryAlpha2::JO,
            Country::Kazakhstan => CountryAlpha2::KZ,
            Country::Kenya => CountryAlpha2::KE,
            Country::Kiribati => CountryAlpha2::KI,
            Country::KoreaDemocraticPeoplesRepublicof => CountryAlpha2::KP,
            Country::KoreaRepublicof => CountryAlpha2::KR,
            Country::Kuwait => CountryAlpha2::KW,
            Country::Kyrgyzstan => CountryAlpha2::KG,
            Country::LaoPeoplesDemocraticRepublic => CountryAlpha2::LA,
            Country::Latvia => CountryAlpha2::LV,
            Country::Lebanon => CountryAlpha2::LB,
            Country::Lesotho => CountryAlpha2::LS,
            Country::Liberia => CountryAlpha2::LR,
            Country::Libya => CountryAlpha2::LY,
            Country::Liechtenstein => CountryAlpha2::LI,
            Country::Lithuania => CountryAlpha2::LT,
            Country::Luxembourg => CountryAlpha2::LU,
            Country::Macao => CountryAlpha2::MO,
            Country::MacedoniatheformerYugoslavRepublicof => CountryAlpha2::MK,
            Country::Madagascar => CountryAlpha2::MG,
            Country::Malawi => CountryAlpha2::MW,
            Country::Malaysia => CountryAlpha2::MY,
            Country::Maldives => CountryAlpha2::MV,
            Country::Mali => CountryAlpha2::ML,
            Country::Malta => CountryAlpha2::MT,
            Country::MarshallIslands => CountryAlpha2::MH,
            Country::Martinique => CountryAlpha2::MQ,
            Country::Mauritania => CountryAlpha2::MR,
            Country::Mauritius => CountryAlpha2::MU,
            Country::Mayotte => CountryAlpha2::YT,
            Country::Mexico => CountryAlpha2::MX,
            Country::MicronesiaFederatedStatesof => CountryAlpha2::FM,
            Country::MoldovaRepublicof => CountryAlpha2::MD,
            Country::Monaco => CountryAlpha2::MC,
            Country::Mongolia => CountryAlpha2::MN,
            Country::Montenegro => CountryAlpha2::ME,
            Country::Montserrat => CountryAlpha2::MS,
            Country::Morocco => CountryAlpha2::MA,
            Country::Mozambique => CountryAlpha2::MZ,
            Country::Myanmar => CountryAlpha2::MM,
            Country::Namibia => CountryAlpha2::NA,
            Country::Nauru => CountryAlpha2::NR,
            Country::Nepal => CountryAlpha2::NP,
            Country::Netherlands => CountryAlpha2::NL,
            Country::NewCaledonia => CountryAlpha2::NC,
            Country::NewZealand => CountryAlpha2::NZ,
            Country::Nicaragua => CountryAlpha2::NI,
            Country::Niger => CountryAlpha2::NE,
            Country::Nigeria => CountryAlpha2::NG,
            Country::Niue => CountryAlpha2::NU,
            Country::NorfolkIsland => CountryAlpha2::NF,
            Country::NorthernMarianaIslands => CountryAlpha2::MP,
            Country::Norway => CountryAlpha2::NO,
            Country::Oman => CountryAlpha2::OM,
            Country::Pakistan => CountryAlpha2::PK,
            Country::Palau => CountryAlpha2::PW,
            Country::PalestineStateof => CountryAlpha2::PS,
            Country::Panama => CountryAlpha2::PA,
            Country::PapuaNewGuinea => CountryAlpha2::PG,
            Country::Paraguay => CountryAlpha2::PY,
            Country::Peru => CountryAlpha2::PE,
            Country::Philippines => CountryAlpha2::PH,
            Country::Pitcairn => CountryAlpha2::PN,
            Country::Poland => CountryAlpha2::PL,
            Country::Portugal => CountryAlpha2::PT,
            Country::PuertoRico => CountryAlpha2::PR,
            Country::Qatar => CountryAlpha2::QA,
            Country::Réunion => CountryAlpha2::RE,
            Country::Romania => CountryAlpha2::RO,
            Country::RussianFederation => CountryAlpha2::RU,
            Country::Rwanda => CountryAlpha2::RW,
            Country::SaintBarthélemy => CountryAlpha2::BL,
            Country::SaintHelenaAscensionandTristandaCunha => CountryAlpha2::SH,
            Country::SaintKittsandNevis => CountryAlpha2::KN,
            Country::SaintLucia => CountryAlpha2::LC,
            Country::SaintMartinFrenchpart => CountryAlpha2::MF,
            Country::SaintPierreandMiquelon => CountryAlpha2::PM,
            Country::SaintVincentandtheGrenadines => CountryAlpha2::VC,
            Country::Samoa => CountryAlpha2::WS,
            Country::SanMarino => CountryAlpha2::SM,
            Country::SaoTomeandPrincipe => CountryAlpha2::ST,
            Country::SaudiArabia => CountryAlpha2::SA,
            Country::Senegal => CountryAlpha2::SN,
            Country::Serbia => CountryAlpha2::RS,
            Country::Seychelles => CountryAlpha2::SC,
            Country::SierraLeone => CountryAlpha2::SL,
            Country::Singapore => CountryAlpha2::SG,
            Country::SintMaartenDutchpart => CountryAlpha2::SX,
            Country::Slovakia => CountryAlpha2::SK,
            Country::Slovenia => CountryAlpha2::SI,
            Country::SolomonIslands => CountryAlpha2::SB,
            Country::Somalia => CountryAlpha2::SO,
            Country::SouthAfrica => CountryAlpha2::ZA,
            Country::SouthGeorgiaandtheSouthSandwichIslands => CountryAlpha2::GS,
            Country::SouthSudan => CountryAlpha2::SS,
            Country::Spain => CountryAlpha2::ES,
            Country::SriLanka => CountryAlpha2::LK,
            Country::Sudan => CountryAlpha2::SD,
            Country::Suriname => CountryAlpha2::SR,
            Country::SvalbardandJanMayen => CountryAlpha2::SJ,
            Country::Swaziland => CountryAlpha2::SZ,
            Country::Sweden => CountryAlpha2::SE,
            Country::Switzerland => CountryAlpha2::CH,
            Country::SyrianArabRepublic => CountryAlpha2::SY,
            Country::TaiwanProvinceofChina => CountryAlpha2::TW,
            Country::Tajikistan => CountryAlpha2::TJ,
            Country::TanzaniaUnitedRepublicof => CountryAlpha2::TZ,
            Country::Thailand => CountryAlpha2::TH,
            Country::TimorLeste => CountryAlpha2::TL,
            Country::Togo => CountryAlpha2::TG,
            Country::Tokelau => CountryAlpha2::TK,
            Country::Tonga => CountryAlpha2::TO,
            Country::TrinidadandTobago => CountryAlpha2::TT,
            Country::Tunisia => CountryAlpha2::TN,
            Country::Turkey => CountryAlpha2::TR,
            Country::Turkmenistan => CountryAlpha2::TM,
            Country::TurksandCaicosIslands => CountryAlpha2::TC,
            Country::Tuvalu => CountryAlpha2::TV,
            Country::Uganda => CountryAlpha2::UG,
            Country::Ukraine => CountryAlpha2::UA,
            Country::UnitedArabEmirates => CountryAlpha2::AE,
            Country::UnitedKingdomofGreatBritainandNorthernIreland => CountryAlpha2::GB,
            Country::UnitedStatesofAmerica => CountryAlpha2::US,
            Country::UnitedStatesMinorOutlyingIslands => CountryAlpha2::UM,
            Country::Uruguay => CountryAlpha2::UY,
            Country::Uzbekistan => CountryAlpha2::UZ,
            Country::Vanuatu => CountryAlpha2::VU,
            Country::VenezuelaBolivarianRepublicof => CountryAlpha2::VE,
            Country::VietNam => CountryAlpha2::VN,
            Country::VirginIslandsBritish => CountryAlpha2::VG,
            Country::VirginIslandsUS => CountryAlpha2::VI,
            Country::WallisandFutuna => CountryAlpha2::WF,
            Country::WesternSahara => CountryAlpha2::EH,
            Country::Yemen => CountryAlpha2::YE,
            Country::Zambia => CountryAlpha2::ZM,
            Country::Zimbabwe => CountryAlpha2::ZW,
        }
    }
    pub const fn from_alpha3(code: CountryAlpha3) -> Self {
        match code {
            CountryAlpha3::AFG => Self::Afghanistan,
            CountryAlpha3::ALA => Self::ÅlandIslands,
            CountryAlpha3::ALB => Self::Albania,
            CountryAlpha3::DZA => Self::Algeria,
            CountryAlpha3::ASM => Self::AmericanSamoa,
            CountryAlpha3::AND => Self::Andorra,
            CountryAlpha3::AGO => Self::Angola,
            CountryAlpha3::AIA => Self::Anguilla,
            CountryAlpha3::ATA => Self::Antarctica,
            CountryAlpha3::ATG => Self::AntiguaandBarbuda,
            CountryAlpha3::ARG => Self::Argentina,
            CountryAlpha3::ARM => Self::Armenia,
            CountryAlpha3::ABW => Self::Aruba,
            CountryAlpha3::AUS => Self::Australia,
            CountryAlpha3::AUT => Self::Austria,
            CountryAlpha3::AZE => Self::Azerbaijan,
            CountryAlpha3::BHS => Self::Bahamas,
            CountryAlpha3::BHR => Self::Bahrain,
            CountryAlpha3::BGD => Self::Bangladesh,
            CountryAlpha3::BRB => Self::Barbados,
            CountryAlpha3::BLR => Self::Belarus,
            CountryAlpha3::BEL => Self::Belgium,
            CountryAlpha3::BLZ => Self::Belize,
            CountryAlpha3::BEN => Self::Benin,
            CountryAlpha3::BMU => Self::Bermuda,
            CountryAlpha3::BTN => Self::Bhutan,
            CountryAlpha3::BOL => Self::BoliviaPlurinationalStateof,
            CountryAlpha3::BES => Self::BonaireSintEustatiusandSaba,
            CountryAlpha3::BIH => Self::BosniaandHerzegovina,
            CountryAlpha3::BWA => Self::Botswana,
            CountryAlpha3::BVT => Self::BouvetIsland,
            CountryAlpha3::BRA => Self::Brazil,
            CountryAlpha3::IOT => Self::BritishIndianOceanTerritory,
            CountryAlpha3::BRN => Self::BruneiDarussalam,
            CountryAlpha3::BGR => Self::Bulgaria,
            CountryAlpha3::BFA => Self::BurkinaFaso,
            CountryAlpha3::BDI => Self::Burundi,
            CountryAlpha3::CPV => Self::CaboVerde,
            CountryAlpha3::KHM => Self::Cambodia,
            CountryAlpha3::CMR => Self::Cameroon,
            CountryAlpha3::CAN => Self::Canada,
            CountryAlpha3::CYM => Self::CaymanIslands,
            CountryAlpha3::CAF => Self::CentralAfricanRepublic,
            CountryAlpha3::TCD => Self::Chad,
            CountryAlpha3::CHL => Self::Chile,
            CountryAlpha3::CHN => Self::China,
            CountryAlpha3::CXR => Self::ChristmasIsland,
            CountryAlpha3::CCK => Self::CocosKeelingIslands,
            CountryAlpha3::COL => Self::Colombia,
            CountryAlpha3::COM => Self::Comoros,
            CountryAlpha3::COG => Self::Congo,
            CountryAlpha3::COD => Self::CongoDemocraticRepublicofthe,
            CountryAlpha3::COK => Self::CookIslands,
            CountryAlpha3::CRI => Self::CostaRica,
            CountryAlpha3::CIV => Self::CôtedIvoire,
            CountryAlpha3::HRV => Self::Croatia,
            CountryAlpha3::CUB => Self::Cuba,
            CountryAlpha3::CUW => Self::Curaçao,
            CountryAlpha3::CYP => Self::Cyprus,
            CountryAlpha3::CZE => Self::Czechia,
            CountryAlpha3::DNK => Self::Denmark,
            CountryAlpha3::DJI => Self::Djibouti,
            CountryAlpha3::DMA => Self::Dominica,
            CountryAlpha3::DOM => Self::DominicanRepublic,
            CountryAlpha3::ECU => Self::Ecuador,
            CountryAlpha3::EGY => Self::Egypt,
            CountryAlpha3::SLV => Self::ElSalvador,
            CountryAlpha3::GNQ => Self::EquatorialGuinea,
            CountryAlpha3::ERI => Self::Eritrea,
            CountryAlpha3::EST => Self::Estonia,
            CountryAlpha3::ETH => Self::Ethiopia,
            CountryAlpha3::FLK => Self::FalklandIslandsMalvinas,
            CountryAlpha3::FRO => Self::FaroeIslands,
            CountryAlpha3::FJI => Self::Fiji,
            CountryAlpha3::FIN => Self::Finland,
            CountryAlpha3::FRA => Self::France,
            CountryAlpha3::GUF => Self::FrenchGuiana,
            CountryAlpha3::PYF => Self::FrenchPolynesia,
            CountryAlpha3::ATF => Self::FrenchSouthernTerritories,
            CountryAlpha3::GAB => Self::Gabon,
            CountryAlpha3::GMB => Self::Gambia,
            CountryAlpha3::GEO => Self::Georgia,
            CountryAlpha3::DEU => Self::Germany,
            CountryAlpha3::GHA => Self::Ghana,
            CountryAlpha3::GIB => Self::Gibraltar,
            CountryAlpha3::GRC => Self::Greece,
            CountryAlpha3::GRL => Self::Greenland,
            CountryAlpha3::GRD => Self::Grenada,
            CountryAlpha3::GLP => Self::Guadeloupe,
            CountryAlpha3::GUM => Self::Guam,
            CountryAlpha3::GTM => Self::Guatemala,
            CountryAlpha3::GGY => Self::Guernsey,
            CountryAlpha3::GIN => Self::Guinea,
            CountryAlpha3::GNB => Self::GuineaBissau,
            CountryAlpha3::GUY => Self::Guyana,
            CountryAlpha3::HTI => Self::Haiti,
            CountryAlpha3::HMD => Self::HeardIslandandMcDonaldIslands,
            CountryAlpha3::VAT => Self::HolySee,
            CountryAlpha3::HND => Self::Honduras,
            CountryAlpha3::HKG => Self::HongKong,
            CountryAlpha3::HUN => Self::Hungary,
            CountryAlpha3::ISL => Self::Iceland,
            CountryAlpha3::IND => Self::India,
            CountryAlpha3::IDN => Self::Indonesia,
            CountryAlpha3::IRN => Self::IranIslamicRepublicof,
            CountryAlpha3::IRQ => Self::Iraq,
            CountryAlpha3::IRL => Self::Ireland,
            CountryAlpha3::IMN => Self::IsleofMan,
            CountryAlpha3::ISR => Self::Israel,
            CountryAlpha3::ITA => Self::Italy,
            CountryAlpha3::JAM => Self::Jamaica,
            CountryAlpha3::JPN => Self::Japan,
            CountryAlpha3::JEY => Self::Jersey,
            CountryAlpha3::JOR => Self::Jordan,
            CountryAlpha3::KAZ => Self::Kazakhstan,
            CountryAlpha3::KEN => Self::Kenya,
            CountryAlpha3::KIR => Self::Kiribati,
            CountryAlpha3::PRK => Self::KoreaDemocraticPeoplesRepublicof,
            CountryAlpha3::KOR => Self::KoreaRepublicof,
            CountryAlpha3::KWT => Self::Kuwait,
            CountryAlpha3::KGZ => Self::Kyrgyzstan,
            CountryAlpha3::LAO => Self::LaoPeoplesDemocraticRepublic,
            CountryAlpha3::LVA => Self::Latvia,
            CountryAlpha3::LBN => Self::Lebanon,
            CountryAlpha3::LSO => Self::Lesotho,
            CountryAlpha3::LBR => Self::Liberia,
            CountryAlpha3::LBY => Self::Libya,
            CountryAlpha3::LIE => Self::Liechtenstein,
            CountryAlpha3::LTU => Self::Lithuania,
            CountryAlpha3::LUX => Self::Luxembourg,
            CountryAlpha3::MAC => Self::Macao,
            CountryAlpha3::MKD => Self::MacedoniatheformerYugoslavRepublicof,
            CountryAlpha3::MDG => Self::Madagascar,
            CountryAlpha3::MWI => Self::Malawi,
            CountryAlpha3::MYS => Self::Malaysia,
            CountryAlpha3::MDV => Self::Maldives,
            CountryAlpha3::MLI => Self::Mali,
            CountryAlpha3::MLT => Self::Malta,
            CountryAlpha3::MHL => Self::MarshallIslands,
            CountryAlpha3::MTQ => Self::Martinique,
            CountryAlpha3::MRT => Self::Mauritania,
            CountryAlpha3::MUS => Self::Mauritius,
            CountryAlpha3::MYT => Self::Mayotte,
            CountryAlpha3::MEX => Self::Mexico,
            CountryAlpha3::FSM => Self::MicronesiaFederatedStatesof,
            CountryAlpha3::MDA => Self::MoldovaRepublicof,
            CountryAlpha3::MCO => Self::Monaco,
            CountryAlpha3::MNG => Self::Mongolia,
            CountryAlpha3::MNE => Self::Montenegro,
            CountryAlpha3::MSR => Self::Montserrat,
            CountryAlpha3::MAR => Self::Morocco,
            CountryAlpha3::MOZ => Self::Mozambique,
            CountryAlpha3::MMR => Self::Myanmar,
            CountryAlpha3::NAM => Self::Namibia,
            CountryAlpha3::NRU => Self::Nauru,
            CountryAlpha3::NPL => Self::Nepal,
            CountryAlpha3::NLD => Self::Netherlands,
            CountryAlpha3::NCL => Self::NewCaledonia,
            CountryAlpha3::NZL => Self::NewZealand,
            CountryAlpha3::NIC => Self::Nicaragua,
            CountryAlpha3::NER => Self::Niger,
            CountryAlpha3::NGA => Self::Nigeria,
            CountryAlpha3::NIU => Self::Niue,
            CountryAlpha3::NFK => Self::NorfolkIsland,
            CountryAlpha3::MNP => Self::NorthernMarianaIslands,
            CountryAlpha3::NOR => Self::Norway,
            CountryAlpha3::OMN => Self::Oman,
            CountryAlpha3::PAK => Self::Pakistan,
            CountryAlpha3::PLW => Self::Palau,
            CountryAlpha3::PSE => Self::PalestineStateof,
            CountryAlpha3::PAN => Self::Panama,
            CountryAlpha3::PNG => Self::PapuaNewGuinea,
            CountryAlpha3::PRY => Self::Paraguay,
            CountryAlpha3::PER => Self::Peru,
            CountryAlpha3::PHL => Self::Philippines,
            CountryAlpha3::PCN => Self::Pitcairn,
            CountryAlpha3::POL => Self::Poland,
            CountryAlpha3::PRT => Self::Portugal,
            CountryAlpha3::PRI => Self::PuertoRico,
            CountryAlpha3::QAT => Self::Qatar,
            CountryAlpha3::REU => Self::Réunion,
            CountryAlpha3::ROU => Self::Romania,
            CountryAlpha3::RUS => Self::RussianFederation,
            CountryAlpha3::RWA => Self::Rwanda,
            CountryAlpha3::BLM => Self::SaintBarthélemy,
            CountryAlpha3::SHN => Self::SaintHelenaAscensionandTristandaCunha,
            CountryAlpha3::KNA => Self::SaintKittsandNevis,
            CountryAlpha3::LCA => Self::SaintLucia,
            CountryAlpha3::MAF => Self::SaintMartinFrenchpart,
            CountryAlpha3::SPM => Self::SaintPierreandMiquelon,
            CountryAlpha3::VCT => Self::SaintVincentandtheGrenadines,
            CountryAlpha3::WSM => Self::Samoa,
            CountryAlpha3::SMR => Self::SanMarino,
            CountryAlpha3::STP => Self::SaoTomeandPrincipe,
            CountryAlpha3::SAU => Self::SaudiArabia,
            CountryAlpha3::SEN => Self::Senegal,
            CountryAlpha3::SRB => Self::Serbia,
            CountryAlpha3::SYC => Self::Seychelles,
            CountryAlpha3::SLE => Self::SierraLeone,
            CountryAlpha3::SGP => Self::Singapore,
            CountryAlpha3::SXM => Self::SintMaartenDutchpart,
            CountryAlpha3::SVK => Self::Slovakia,
            CountryAlpha3::SVN => Self::Slovenia,
            CountryAlpha3::SLB => Self::SolomonIslands,
            CountryAlpha3::SOM => Self::Somalia,
            CountryAlpha3::ZAF => Self::SouthAfrica,
            CountryAlpha3::SGS => Self::SouthGeorgiaandtheSouthSandwichIslands,
            CountryAlpha3::SSD => Self::SouthSudan,
            CountryAlpha3::ESP => Self::Spain,
            CountryAlpha3::LKA => Self::SriLanka,
            CountryAlpha3::SDN => Self::Sudan,
            CountryAlpha3::SUR => Self::Suriname,
            CountryAlpha3::SJM => Self::SvalbardandJanMayen,
            CountryAlpha3::SWZ => Self::Swaziland,
            CountryAlpha3::SWE => Self::Sweden,
            CountryAlpha3::CHE => Self::Switzerland,
            CountryAlpha3::SYR => Self::SyrianArabRepublic,
            CountryAlpha3::TWN => Self::TaiwanProvinceofChina,
            CountryAlpha3::TJK => Self::Tajikistan,
            CountryAlpha3::TZA => Self::TanzaniaUnitedRepublicof,
            CountryAlpha3::THA => Self::Thailand,
            CountryAlpha3::TLS => Self::TimorLeste,
            CountryAlpha3::TGO => Self::Togo,
            CountryAlpha3::TKL => Self::Tokelau,
            CountryAlpha3::TON => Self::Tonga,
            CountryAlpha3::TTO => Self::TrinidadandTobago,
            CountryAlpha3::TUN => Self::Tunisia,
            CountryAlpha3::TUR => Self::Turkey,
            CountryAlpha3::TKM => Self::Turkmenistan,
            CountryAlpha3::TCA => Self::TurksandCaicosIslands,
            CountryAlpha3::TUV => Self::Tuvalu,
            CountryAlpha3::UGA => Self::Uganda,
            CountryAlpha3::UKR => Self::Ukraine,
            CountryAlpha3::ARE => Self::UnitedArabEmirates,
            CountryAlpha3::GBR => Self::UnitedKingdomofGreatBritainandNorthernIreland,
            CountryAlpha3::USA => Self::UnitedStatesofAmerica,
            CountryAlpha3::UMI => Self::UnitedStatesMinorOutlyingIslands,
            CountryAlpha3::URY => Self::Uruguay,
            CountryAlpha3::UZB => Self::Uzbekistan,
            CountryAlpha3::VUT => Self::Vanuatu,
            CountryAlpha3::VEN => Self::VenezuelaBolivarianRepublicof,
            CountryAlpha3::VNM => Self::VietNam,
            CountryAlpha3::VGB => Self::VirginIslandsBritish,
            CountryAlpha3::VIR => Self::VirginIslandsUS,
            CountryAlpha3::WLF => Self::WallisandFutuna,
            CountryAlpha3::ESH => Self::WesternSahara,
            CountryAlpha3::YEM => Self::Yemen,
            CountryAlpha3::ZMB => Self::Zambia,
            CountryAlpha3::ZWE => Self::Zimbabwe,
        }
    }
    pub const fn to_alpha3(&self) -> CountryAlpha3 {
        match self {
            Country::Afghanistan => CountryAlpha3::AFG,
            Country::ÅlandIslands => CountryAlpha3::ALA,
            Country::Albania => CountryAlpha3::ALB,
            Country::Algeria => CountryAlpha3::DZA,
            Country::AmericanSamoa => CountryAlpha3::ASM,
            Country::Andorra => CountryAlpha3::AND,
            Country::Angola => CountryAlpha3::AGO,
            Country::Anguilla => CountryAlpha3::AIA,
            Country::Antarctica => CountryAlpha3::ATA,
            Country::AntiguaandBarbuda => CountryAlpha3::ATG,
            Country::Argentina => CountryAlpha3::ARG,
            Country::Armenia => CountryAlpha3::ARM,
            Country::Aruba => CountryAlpha3::ABW,
            Country::Australia => CountryAlpha3::AUS,
            Country::Austria => CountryAlpha3::AUT,
            Country::Azerbaijan => CountryAlpha3::AZE,
            Country::Bahamas => CountryAlpha3::BHS,
            Country::Bahrain => CountryAlpha3::BHR,
            Country::Bangladesh => CountryAlpha3::BGD,
            Country::Barbados => CountryAlpha3::BRB,
            Country::Belarus => CountryAlpha3::BLR,
            Country::Belgium => CountryAlpha3::BEL,
            Country::Belize => CountryAlpha3::BLZ,
            Country::Benin => CountryAlpha3::BEN,
            Country::Bermuda => CountryAlpha3::BMU,
            Country::Bhutan => CountryAlpha3::BTN,
            Country::BoliviaPlurinationalStateof => CountryAlpha3::BOL,
            Country::BonaireSintEustatiusandSaba => CountryAlpha3::BES,
            Country::BosniaandHerzegovina => CountryAlpha3::BIH,
            Country::Botswana => CountryAlpha3::BWA,
            Country::BouvetIsland => CountryAlpha3::BVT,
            Country::Brazil => CountryAlpha3::BRA,
            Country::BritishIndianOceanTerritory => CountryAlpha3::IOT,
            Country::BruneiDarussalam => CountryAlpha3::BRN,
            Country::Bulgaria => CountryAlpha3::BGR,
            Country::BurkinaFaso => CountryAlpha3::BFA,
            Country::Burundi => CountryAlpha3::BDI,
            Country::CaboVerde => CountryAlpha3::CPV,
            Country::Cambodia => CountryAlpha3::KHM,
            Country::Cameroon => CountryAlpha3::CMR,
            Country::Canada => CountryAlpha3::CAN,
            Country::CaymanIslands => CountryAlpha3::CYM,
            Country::CentralAfricanRepublic => CountryAlpha3::CAF,
            Country::Chad => CountryAlpha3::TCD,
            Country::Chile => CountryAlpha3::CHL,
            Country::China => CountryAlpha3::CHN,
            Country::ChristmasIsland => CountryAlpha3::CXR,
            Country::CocosKeelingIslands => CountryAlpha3::CCK,
            Country::Colombia => CountryAlpha3::COL,
            Country::Comoros => CountryAlpha3::COM,
            Country::Congo => CountryAlpha3::COG,
            Country::CongoDemocraticRepublicofthe => CountryAlpha3::COD,
            Country::CookIslands => CountryAlpha3::COK,
            Country::CostaRica => CountryAlpha3::CRI,
            Country::CôtedIvoire => CountryAlpha3::CIV,
            Country::Croatia => CountryAlpha3::HRV,
            Country::Cuba => CountryAlpha3::CUB,
            Country::Curaçao => CountryAlpha3::CUW,
            Country::Cyprus => CountryAlpha3::CYP,
            Country::Czechia => CountryAlpha3::CZE,
            Country::Denmark => CountryAlpha3::DNK,
            Country::Djibouti => CountryAlpha3::DJI,
            Country::Dominica => CountryAlpha3::DMA,
            Country::DominicanRepublic => CountryAlpha3::DOM,
            Country::Ecuador => CountryAlpha3::ECU,
            Country::Egypt => CountryAlpha3::EGY,
            Country::ElSalvador => CountryAlpha3::SLV,
            Country::EquatorialGuinea => CountryAlpha3::GNQ,
            Country::Eritrea => CountryAlpha3::ERI,
            Country::Estonia => CountryAlpha3::EST,
            Country::Ethiopia => CountryAlpha3::ETH,
            Country::FalklandIslandsMalvinas => CountryAlpha3::FLK,
            Country::FaroeIslands => CountryAlpha3::FRO,
            Country::Fiji => CountryAlpha3::FJI,
            Country::Finland => CountryAlpha3::FIN,
            Country::France => CountryAlpha3::FRA,
            Country::FrenchGuiana => CountryAlpha3::GUF,
            Country::FrenchPolynesia => CountryAlpha3::PYF,
            Country::FrenchSouthernTerritories => CountryAlpha3::ATF,
            Country::Gabon => CountryAlpha3::GAB,
            Country::Gambia => CountryAlpha3::GMB,
            Country::Georgia => CountryAlpha3::GEO,
            Country::Germany => CountryAlpha3::DEU,
            Country::Ghana => CountryAlpha3::GHA,
            Country::Gibraltar => CountryAlpha3::GIB,
            Country::Greece => CountryAlpha3::GRC,
            Country::Greenland => CountryAlpha3::GRL,
            Country::Grenada => CountryAlpha3::GRD,
            Country::Guadeloupe => CountryAlpha3::GLP,
            Country::Guam => CountryAlpha3::GUM,
            Country::Guatemala => CountryAlpha3::GTM,
            Country::Guernsey => CountryAlpha3::GGY,
            Country::Guinea => CountryAlpha3::GIN,
            Country::GuineaBissau => CountryAlpha3::GNB,
            Country::Guyana => CountryAlpha3::GUY,
            Country::Haiti => CountryAlpha3::HTI,
            Country::HeardIslandandMcDonaldIslands => CountryAlpha3::HMD,
            Country::HolySee => CountryAlpha3::VAT,
            Country::Honduras => CountryAlpha3::HND,
            Country::HongKong => CountryAlpha3::HKG,
            Country::Hungary => CountryAlpha3::HUN,
            Country::Iceland => CountryAlpha3::ISL,
            Country::India => CountryAlpha3::IND,
            Country::Indonesia => CountryAlpha3::IDN,
            Country::IranIslamicRepublicof => CountryAlpha3::IRN,
            Country::Iraq => CountryAlpha3::IRQ,
            Country::Ireland => CountryAlpha3::IRL,
            Country::IsleofMan => CountryAlpha3::IMN,
            Country::Israel => CountryAlpha3::ISR,
            Country::Italy => CountryAlpha3::ITA,
            Country::Jamaica => CountryAlpha3::JAM,
            Country::Japan => CountryAlpha3::JPN,
            Country::Jersey => CountryAlpha3::JEY,
            Country::Jordan => CountryAlpha3::JOR,
            Country::Kazakhstan => CountryAlpha3::KAZ,
            Country::Kenya => CountryAlpha3::KEN,
            Country::Kiribati => CountryAlpha3::KIR,
            Country::KoreaDemocraticPeoplesRepublicof => CountryAlpha3::PRK,
            Country::KoreaRepublicof => CountryAlpha3::KOR,
            Country::Kuwait => CountryAlpha3::KWT,
            Country::Kyrgyzstan => CountryAlpha3::KGZ,
            Country::LaoPeoplesDemocraticRepublic => CountryAlpha3::LAO,
            Country::Latvia => CountryAlpha3::LVA,
            Country::Lebanon => CountryAlpha3::LBN,
            Country::Lesotho => CountryAlpha3::LSO,
            Country::Liberia => CountryAlpha3::LBR,
            Country::Libya => CountryAlpha3::LBY,
            Country::Liechtenstein => CountryAlpha3::LIE,
            Country::Lithuania => CountryAlpha3::LTU,
            Country::Luxembourg => CountryAlpha3::LUX,
            Country::Macao => CountryAlpha3::MAC,
            Country::MacedoniatheformerYugoslavRepublicof => CountryAlpha3::MKD,
            Country::Madagascar => CountryAlpha3::MDG,
            Country::Malawi => CountryAlpha3::MWI,
            Country::Malaysia => CountryAlpha3::MYS,
            Country::Maldives => CountryAlpha3::MDV,
            Country::Mali => CountryAlpha3::MLI,
            Country::Malta => CountryAlpha3::MLT,
            Country::MarshallIslands => CountryAlpha3::MHL,
            Country::Martinique => CountryAlpha3::MTQ,
            Country::Mauritania => CountryAlpha3::MRT,
            Country::Mauritius => CountryAlpha3::MUS,
            Country::Mayotte => CountryAlpha3::MYT,
            Country::Mexico => CountryAlpha3::MEX,
            Country::MicronesiaFederatedStatesof => CountryAlpha3::FSM,
            Country::MoldovaRepublicof => CountryAlpha3::MDA,
            Country::Monaco => CountryAlpha3::MCO,
            Country::Mongolia => CountryAlpha3::MNG,
            Country::Montenegro => CountryAlpha3::MNE,
            Country::Montserrat => CountryAlpha3::MSR,
            Country::Morocco => CountryAlpha3::MAR,
            Country::Mozambique => CountryAlpha3::MOZ,
            Country::Myanmar => CountryAlpha3::MMR,
            Country::Namibia => CountryAlpha3::NAM,
            Country::Nauru => CountryAlpha3::NRU,
            Country::Nepal => CountryAlpha3::NPL,
            Country::Netherlands => CountryAlpha3::NLD,
            Country::NewCaledonia => CountryAlpha3::NCL,
            Country::NewZealand => CountryAlpha3::NZL,
            Country::Nicaragua => CountryAlpha3::NIC,
            Country::Niger => CountryAlpha3::NER,
            Country::Nigeria => CountryAlpha3::NGA,
            Country::Niue => CountryAlpha3::NIU,
            Country::NorfolkIsland => CountryAlpha3::NFK,
            Country::NorthernMarianaIslands => CountryAlpha3::MNP,
            Country::Norway => CountryAlpha3::NOR,
            Country::Oman => CountryAlpha3::OMN,
            Country::Pakistan => CountryAlpha3::PAK,
            Country::Palau => CountryAlpha3::PLW,
            Country::PalestineStateof => CountryAlpha3::PSE,
            Country::Panama => CountryAlpha3::PAN,
            Country::PapuaNewGuinea => CountryAlpha3::PNG,
            Country::Paraguay => CountryAlpha3::PRY,
            Country::Peru => CountryAlpha3::PER,
            Country::Philippines => CountryAlpha3::PHL,
            Country::Pitcairn => CountryAlpha3::PCN,
            Country::Poland => CountryAlpha3::POL,
            Country::Portugal => CountryAlpha3::PRT,
            Country::PuertoRico => CountryAlpha3::PRI,
            Country::Qatar => CountryAlpha3::QAT,
            Country::Réunion => CountryAlpha3::REU,
            Country::Romania => CountryAlpha3::ROU,
            Country::RussianFederation => CountryAlpha3::RUS,
            Country::Rwanda => CountryAlpha3::RWA,
            Country::SaintBarthélemy => CountryAlpha3::BLM,
            Country::SaintHelenaAscensionandTristandaCunha => CountryAlpha3::SHN,
            Country::SaintKittsandNevis => CountryAlpha3::KNA,
            Country::SaintLucia => CountryAlpha3::LCA,
            Country::SaintMartinFrenchpart => CountryAlpha3::MAF,
            Country::SaintPierreandMiquelon => CountryAlpha3::SPM,
            Country::SaintVincentandtheGrenadines => CountryAlpha3::VCT,
            Country::Samoa => CountryAlpha3::WSM,
            Country::SanMarino => CountryAlpha3::SMR,
            Country::SaoTomeandPrincipe => CountryAlpha3::STP,
            Country::SaudiArabia => CountryAlpha3::SAU,
            Country::Senegal => CountryAlpha3::SEN,
            Country::Serbia => CountryAlpha3::SRB,
            Country::Seychelles => CountryAlpha3::SYC,
            Country::SierraLeone => CountryAlpha3::SLE,
            Country::Singapore => CountryAlpha3::SGP,
            Country::SintMaartenDutchpart => CountryAlpha3::SXM,
            Country::Slovakia => CountryAlpha3::SVK,
            Country::Slovenia => CountryAlpha3::SVN,
            Country::SolomonIslands => CountryAlpha3::SLB,
            Country::Somalia => CountryAlpha3::SOM,
            Country::SouthAfrica => CountryAlpha3::ZAF,
            Country::SouthGeorgiaandtheSouthSandwichIslands => CountryAlpha3::SGS,
            Country::SouthSudan => CountryAlpha3::SSD,
            Country::Spain => CountryAlpha3::ESP,
            Country::SriLanka => CountryAlpha3::LKA,
            Country::Sudan => CountryAlpha3::SDN,
            Country::Suriname => CountryAlpha3::SUR,
            Country::SvalbardandJanMayen => CountryAlpha3::SJM,
            Country::Swaziland => CountryAlpha3::SWZ,
            Country::Sweden => CountryAlpha3::SWE,
            Country::Switzerland => CountryAlpha3::CHE,
            Country::SyrianArabRepublic => CountryAlpha3::SYR,
            Country::TaiwanProvinceofChina => CountryAlpha3::TWN,
            Country::Tajikistan => CountryAlpha3::TJK,
            Country::TanzaniaUnitedRepublicof => CountryAlpha3::TZA,
            Country::Thailand => CountryAlpha3::THA,
            Country::TimorLeste => CountryAlpha3::TLS,
            Country::Togo => CountryAlpha3::TGO,
            Country::Tokelau => CountryAlpha3::TKL,
            Country::Tonga => CountryAlpha3::TON,
            Country::TrinidadandTobago => CountryAlpha3::TTO,
            Country::Tunisia => CountryAlpha3::TUN,
            Country::Turkey => CountryAlpha3::TUR,
            Country::Turkmenistan => CountryAlpha3::TKM,
            Country::TurksandCaicosIslands => CountryAlpha3::TCA,
            Country::Tuvalu => CountryAlpha3::TUV,
            Country::Uganda => CountryAlpha3::UGA,
            Country::Ukraine => CountryAlpha3::UKR,
            Country::UnitedArabEmirates => CountryAlpha3::ARE,
            Country::UnitedKingdomofGreatBritainandNorthernIreland => CountryAlpha3::GBR,
            Country::UnitedStatesofAmerica => CountryAlpha3::USA,
            Country::UnitedStatesMinorOutlyingIslands => CountryAlpha3::UMI,
            Country::Uruguay => CountryAlpha3::URY,
            Country::Uzbekistan => CountryAlpha3::UZB,
            Country::Vanuatu => CountryAlpha3::VUT,
            Country::VenezuelaBolivarianRepublicof => CountryAlpha3::VEN,
            Country::VietNam => CountryAlpha3::VNM,
            Country::VirginIslandsBritish => CountryAlpha3::VGB,
            Country::VirginIslandsUS => CountryAlpha3::VIR,
            Country::WallisandFutuna => CountryAlpha3::WLF,
            Country::WesternSahara => CountryAlpha3::ESH,
            Country::Yemen => CountryAlpha3::YEM,
            Country::Zambia => CountryAlpha3::ZMB,
            Country::Zimbabwe => CountryAlpha3::ZWE,
        }
    }
    pub const fn from_numeric(code: u32) -> Self {
        match code {
            4 => Self::Afghanistan,
            248 => Self::ÅlandIslands,
            8 => Self::Albania,
            12 => Self::Algeria,
            16 => Self::AmericanSamoa,
            20 => Self::Andorra,
            24 => Self::Angola,
            660 => Self::Anguilla,
            10 => Self::Antarctica,
            28 => Self::AntiguaandBarbuda,
            32 => Self::Argentina,
            51 => Self::Armenia,
            533 => Self::Aruba,
            36 => Self::Australia,
            40 => Self::Austria,
            31 => Self::Azerbaijan,
            44 => Self::Bahamas,
            48 => Self::Bahrain,
            50 => Self::Bangladesh,
            52 => Self::Barbados,
            112 => Self::Belarus,
            56 => Self::Belgium,
            84 => Self::Belize,
            204 => Self::Benin,
            60 => Self::Bermuda,
            64 => Self::Bhutan,
            68 => Self::BoliviaPlurinationalStateof,
            535 => Self::BonaireSintEustatiusandSaba,
            70 => Self::BosniaandHerzegovina,
            72 => Self::Botswana,
            74 => Self::BouvetIsland,
            76 => Self::Brazil,
            86 => Self::BritishIndianOceanTerritory,
            96 => Self::BruneiDarussalam,
            100 => Self::Bulgaria,
            854 => Self::BurkinaFaso,
            108 => Self::Burundi,
            132 => Self::CaboVerde,
            116 => Self::Cambodia,
            120 => Self::Cameroon,
            124 => Self::Canada,
            136 => Self::CaymanIslands,
            140 => Self::CentralAfricanRepublic,
            148 => Self::Chad,
            152 => Self::Chile,
            156 => Self::China,
            162 => Self::ChristmasIsland,
            166 => Self::CocosKeelingIslands,
            170 => Self::Colombia,
            174 => Self::Comoros,
            178 => Self::Congo,
            180 => Self::CongoDemocraticRepublicofthe,
            184 => Self::CookIslands,
            188 => Self::CostaRica,
            384 => Self::CôtedIvoire,
            191 => Self::Croatia,
            192 => Self::Cuba,
            531 => Self::Curaçao,
            196 => Self::Cyprus,
            203 => Self::Czechia,
            208 => Self::Denmark,
            262 => Self::Djibouti,
            212 => Self::Dominica,
            214 => Self::DominicanRepublic,
            218 => Self::Ecuador,
            818 => Self::Egypt,
            222 => Self::ElSalvador,
            226 => Self::EquatorialGuinea,
            232 => Self::Eritrea,
            233 => Self::Estonia,
            231 => Self::Ethiopia,
            238 => Self::FalklandIslandsMalvinas,
            234 => Self::FaroeIslands,
            242 => Self::Fiji,
            246 => Self::Finland,
            250 => Self::France,
            254 => Self::FrenchGuiana,
            258 => Self::FrenchPolynesia,
            260 => Self::FrenchSouthernTerritories,
            266 => Self::Gabon,
            270 => Self::Gambia,
            268 => Self::Georgia,
            276 => Self::Germany,
            288 => Self::Ghana,
            292 => Self::Gibraltar,
            300 => Self::Greece,
            304 => Self::Greenland,
            308 => Self::Grenada,
            312 => Self::Guadeloupe,
            316 => Self::Guam,
            320 => Self::Guatemala,
            831 => Self::Guernsey,
            324 => Self::Guinea,
            624 => Self::GuineaBissau,
            328 => Self::Guyana,
            332 => Self::Haiti,
            334 => Self::HeardIslandandMcDonaldIslands,
            336 => Self::HolySee,
            340 => Self::Honduras,
            344 => Self::HongKong,
            348 => Self::Hungary,
            352 => Self::Iceland,
            356 => Self::India,
            360 => Self::Indonesia,
            364 => Self::IranIslamicRepublicof,
            368 => Self::Iraq,
            372 => Self::Ireland,
            833 => Self::IsleofMan,
            376 => Self::Israel,
            380 => Self::Italy,
            388 => Self::Jamaica,
            392 => Self::Japan,
            832 => Self::Jersey,
            400 => Self::Jordan,
            398 => Self::Kazakhstan,
            404 => Self::Kenya,
            296 => Self::Kiribati,
            408 => Self::KoreaDemocraticPeoplesRepublicof,
            410 => Self::KoreaRepublicof,
            414 => Self::Kuwait,
            417 => Self::Kyrgyzstan,
            418 => Self::LaoPeoplesDemocraticRepublic,
            428 => Self::Latvia,
            422 => Self::Lebanon,
            426 => Self::Lesotho,
            430 => Self::Liberia,
            434 => Self::Libya,
            438 => Self::Liechtenstein,
            440 => Self::Lithuania,
            442 => Self::Luxembourg,
            446 => Self::Macao,
            807 => Self::MacedoniatheformerYugoslavRepublicof,
            450 => Self::Madagascar,
            454 => Self::Malawi,
            458 => Self::Malaysia,
            462 => Self::Maldives,
            466 => Self::Mali,
            470 => Self::Malta,
            584 => Self::MarshallIslands,
            474 => Self::Martinique,
            478 => Self::Mauritania,
            480 => Self::Mauritius,
            175 => Self::Mayotte,
            484 => Self::Mexico,
            583 => Self::MicronesiaFederatedStatesof,
            498 => Self::MoldovaRepublicof,
            492 => Self::Monaco,
            496 => Self::Mongolia,
            499 => Self::Montenegro,
            500 => Self::Montserrat,
            504 => Self::Morocco,
            508 => Self::Mozambique,
            104 => Self::Myanmar,
            516 => Self::Namibia,
            520 => Self::Nauru,
            524 => Self::Nepal,
            528 => Self::Netherlands,
            540 => Self::NewCaledonia,
            554 => Self::NewZealand,
            558 => Self::Nicaragua,
            562 => Self::Niger,
            566 => Self::Nigeria,
            570 => Self::Niue,
            574 => Self::NorfolkIsland,
            580 => Self::NorthernMarianaIslands,
            578 => Self::Norway,
            512 => Self::Oman,
            586 => Self::Pakistan,
            585 => Self::Palau,
            275 => Self::PalestineStateof,
            591 => Self::Panama,
            598 => Self::PapuaNewGuinea,
            600 => Self::Paraguay,
            604 => Self::Peru,
            608 => Self::Philippines,
            612 => Self::Pitcairn,
            616 => Self::Poland,
            620 => Self::Portugal,
            630 => Self::PuertoRico,
            634 => Self::Qatar,
            638 => Self::Réunion,
            642 => Self::Romania,
            643 => Self::RussianFederation,
            646 => Self::Rwanda,
            652 => Self::SaintBarthélemy,
            654 => Self::SaintHelenaAscensionandTristandaCunha,
            659 => Self::SaintKittsandNevis,
            662 => Self::SaintLucia,
            663 => Self::SaintMartinFrenchpart,
            666 => Self::SaintPierreandMiquelon,
            670 => Self::SaintVincentandtheGrenadines,
            882 => Self::Samoa,
            674 => Self::SanMarino,
            678 => Self::SaoTomeandPrincipe,
            682 => Self::SaudiArabia,
            686 => Self::Senegal,
            688 => Self::Serbia,
            690 => Self::Seychelles,
            694 => Self::SierraLeone,
            702 => Self::Singapore,
            534 => Self::SintMaartenDutchpart,
            703 => Self::Slovakia,
            705 => Self::Slovenia,
            90 => Self::SolomonIslands,
            706 => Self::Somalia,
            710 => Self::SouthAfrica,
            239 => Self::SouthGeorgiaandtheSouthSandwichIslands,
            728 => Self::SouthSudan,
            724 => Self::Spain,
            144 => Self::SriLanka,
            729 => Self::Sudan,
            740 => Self::Suriname,
            744 => Self::SvalbardandJanMayen,
            748 => Self::Swaziland,
            752 => Self::Sweden,
            756 => Self::Switzerland,
            760 => Self::SyrianArabRepublic,
            158 => Self::TaiwanProvinceofChina,
            762 => Self::Tajikistan,
            834 => Self::TanzaniaUnitedRepublicof,
            764 => Self::Thailand,
            626 => Self::TimorLeste,
            768 => Self::Togo,
            772 => Self::Tokelau,
            776 => Self::Tonga,
            780 => Self::TrinidadandTobago,
            788 => Self::Tunisia,
            792 => Self::Turkey,
            795 => Self::Turkmenistan,
            796 => Self::TurksandCaicosIslands,
            798 => Self::Tuvalu,
            800 => Self::Uganda,
            804 => Self::Ukraine,
            784 => Self::UnitedArabEmirates,
            826 => Self::UnitedKingdomofGreatBritainandNorthernIreland,
            840 => Self::UnitedStatesofAmerica,
            581 => Self::UnitedStatesMinorOutlyingIslands,
            858 => Self::Uruguay,
            860 => Self::Uzbekistan,
            548 => Self::Vanuatu,
            862 => Self::VenezuelaBolivarianRepublicof,
            704 => Self::VietNam,
            92 => Self::VirginIslandsBritish,
            850 => Self::VirginIslandsUS,
            876 => Self::WallisandFutuna,
            732 => Self::WesternSahara,
            887 => Self::Yemen,
            894 => Self::Zambia,
            716 => Self::Zimbabwe,
            _ => {
                panic!()
            }
        }
    }
    pub const fn to_numeric(&self) -> u32 {
        match self {
            Country::Afghanistan => 4,
            Country::ÅlandIslands => 248,
            Country::Albania => 8,
            Country::Algeria => 12,
            Country::AmericanSamoa => 16,
            Country::Andorra => 20,
            Country::Angola => 24,
            Country::Anguilla => 660,
            Country::Antarctica => 10,
            Country::AntiguaandBarbuda => 28,
            Country::Argentina => 32,
            Country::Armenia => 51,
            Country::Aruba => 533,
            Country::Australia => 36,
            Country::Austria => 40,
            Country::Azerbaijan => 31,
            Country::Bahamas => 44,
            Country::Bahrain => 48,
            Country::Bangladesh => 50,
            Country::Barbados => 52,
            Country::Belarus => 112,
            Country::Belgium => 56,
            Country::Belize => 84,
            Country::Benin => 204,
            Country::Bermuda => 60,
            Country::Bhutan => 64,
            Country::BoliviaPlurinationalStateof => 68,
            Country::BonaireSintEustatiusandSaba => 535,
            Country::BosniaandHerzegovina => 70,
            Country::Botswana => 72,
            Country::BouvetIsland => 74,
            Country::Brazil => 76,
            Country::BritishIndianOceanTerritory => 86,
            Country::BruneiDarussalam => 96,
            Country::Bulgaria => 100,
            Country::BurkinaFaso => 854,
            Country::Burundi => 108,
            Country::CaboVerde => 132,
            Country::Cambodia => 116,
            Country::Cameroon => 120,
            Country::Canada => 124,
            Country::CaymanIslands => 136,
            Country::CentralAfricanRepublic => 140,
            Country::Chad => 148,
            Country::Chile => 152,
            Country::China => 156,
            Country::ChristmasIsland => 162,
            Country::CocosKeelingIslands => 166,
            Country::Colombia => 170,
            Country::Comoros => 174,
            Country::Congo => 178,
            Country::CongoDemocraticRepublicofthe => 180,
            Country::CookIslands => 184,
            Country::CostaRica => 188,
            Country::CôtedIvoire => 384,
            Country::Croatia => 191,
            Country::Cuba => 192,
            Country::Curaçao => 531,
            Country::Cyprus => 196,
            Country::Czechia => 203,
            Country::Denmark => 208,
            Country::Djibouti => 262,
            Country::Dominica => 212,
            Country::DominicanRepublic => 214,
            Country::Ecuador => 218,
            Country::Egypt => 818,
            Country::ElSalvador => 222,
            Country::EquatorialGuinea => 226,
            Country::Eritrea => 232,
            Country::Estonia => 233,
            Country::Ethiopia => 231,
            Country::FalklandIslandsMalvinas => 238,
            Country::FaroeIslands => 234,
            Country::Fiji => 242,
            Country::Finland => 246,
            Country::France => 250,
            Country::FrenchGuiana => 254,
            Country::FrenchPolynesia => 258,
            Country::FrenchSouthernTerritories => 260,
            Country::Gabon => 266,
            Country::Gambia => 270,
            Country::Georgia => 268,
            Country::Germany => 276,
            Country::Ghana => 288,
            Country::Gibraltar => 292,
            Country::Greece => 300,
            Country::Greenland => 304,
            Country::Grenada => 308,
            Country::Guadeloupe => 312,
            Country::Guam => 316,
            Country::Guatemala => 320,
            Country::Guernsey => 831,
            Country::Guinea => 324,
            Country::GuineaBissau => 624,
            Country::Guyana => 328,
            Country::Haiti => 332,
            Country::HeardIslandandMcDonaldIslands => 334,
            Country::HolySee => 336,
            Country::Honduras => 340,
            Country::HongKong => 344,
            Country::Hungary => 348,
            Country::Iceland => 352,
            Country::India => 356,
            Country::Indonesia => 360,
            Country::IranIslamicRepublicof => 364,
            Country::Iraq => 368,
            Country::Ireland => 372,
            Country::IsleofMan => 833,
            Country::Israel => 376,
            Country::Italy => 380,
            Country::Jamaica => 388,
            Country::Japan => 392,
            Country::Jersey => 832,
            Country::Jordan => 400,
            Country::Kazakhstan => 398,
            Country::Kenya => 404,
            Country::Kiribati => 296,
            Country::KoreaDemocraticPeoplesRepublicof => 408,
            Country::KoreaRepublicof => 410,
            Country::Kuwait => 414,
            Country::Kyrgyzstan => 417,
            Country::LaoPeoplesDemocraticRepublic => 418,
            Country::Latvia => 428,
            Country::Lebanon => 422,
            Country::Lesotho => 426,
            Country::Liberia => 430,
            Country::Libya => 434,
            Country::Liechtenstein => 438,
            Country::Lithuania => 440,
            Country::Luxembourg => 442,
            Country::Macao => 446,
            Country::MacedoniatheformerYugoslavRepublicof => 807,
            Country::Madagascar => 450,
            Country::Malawi => 454,
            Country::Malaysia => 458,
            Country::Maldives => 462,
            Country::Mali => 466,
            Country::Malta => 470,
            Country::MarshallIslands => 584,
            Country::Martinique => 474,
            Country::Mauritania => 478,
            Country::Mauritius => 480,
            Country::Mayotte => 175,
            Country::Mexico => 484,
            Country::MicronesiaFederatedStatesof => 583,
            Country::MoldovaRepublicof => 498,
            Country::Monaco => 492,
            Country::Mongolia => 496,
            Country::Montenegro => 499,
            Country::Montserrat => 500,
            Country::Morocco => 504,
            Country::Mozambique => 508,
            Country::Myanmar => 104,
            Country::Namibia => 516,
            Country::Nauru => 520,
            Country::Nepal => 524,
            Country::Netherlands => 528,
            Country::NewCaledonia => 540,
            Country::NewZealand => 554,
            Country::Nicaragua => 558,
            Country::Niger => 562,
            Country::Nigeria => 566,
            Country::Niue => 570,
            Country::NorfolkIsland => 574,
            Country::NorthernMarianaIslands => 580,
            Country::Norway => 578,
            Country::Oman => 512,
            Country::Pakistan => 586,
            Country::Palau => 585,
            Country::PalestineStateof => 275,
            Country::Panama => 591,
            Country::PapuaNewGuinea => 598,
            Country::Paraguay => 600,
            Country::Peru => 604,
            Country::Philippines => 608,
            Country::Pitcairn => 612,
            Country::Poland => 616,
            Country::Portugal => 620,
            Country::PuertoRico => 630,
            Country::Qatar => 634,
            Country::Réunion => 638,
            Country::Romania => 642,
            Country::RussianFederation => 643,
            Country::Rwanda => 646,
            Country::SaintBarthélemy => 652,
            Country::SaintHelenaAscensionandTristandaCunha => 654,
            Country::SaintKittsandNevis => 659,
            Country::SaintLucia => 662,
            Country::SaintMartinFrenchpart => 663,
            Country::SaintPierreandMiquelon => 666,
            Country::SaintVincentandtheGrenadines => 670,
            Country::Samoa => 882,
            Country::SanMarino => 674,
            Country::SaoTomeandPrincipe => 678,
            Country::SaudiArabia => 682,
            Country::Senegal => 686,
            Country::Serbia => 688,
            Country::Seychelles => 690,
            Country::SierraLeone => 694,
            Country::Singapore => 702,
            Country::SintMaartenDutchpart => 534,
            Country::Slovakia => 703,
            Country::Slovenia => 705,
            Country::SolomonIslands => 90,
            Country::Somalia => 706,
            Country::SouthAfrica => 710,
            Country::SouthGeorgiaandtheSouthSandwichIslands => 239,
            Country::SouthSudan => 728,
            Country::Spain => 724,
            Country::SriLanka => 144,
            Country::Sudan => 729,
            Country::Suriname => 740,
            Country::SvalbardandJanMayen => 744,
            Country::Swaziland => 748,
            Country::Sweden => 752,
            Country::Switzerland => 756,
            Country::SyrianArabRepublic => 760,
            Country::TaiwanProvinceofChina => 158,
            Country::Tajikistan => 762,
            Country::TanzaniaUnitedRepublicof => 834,
            Country::Thailand => 764,
            Country::TimorLeste => 626,
            Country::Togo => 768,
            Country::Tokelau => 772,
            Country::Tonga => 776,
            Country::TrinidadandTobago => 780,
            Country::Tunisia => 788,
            Country::Turkey => 792,
            Country::Turkmenistan => 795,
            Country::TurksandCaicosIslands => 796,
            Country::Tuvalu => 798,
            Country::Uganda => 800,
            Country::Ukraine => 804,
            Country::UnitedArabEmirates => 784,
            Country::UnitedKingdomofGreatBritainandNorthernIreland => 826,
            Country::UnitedStatesofAmerica => 840,
            Country::UnitedStatesMinorOutlyingIslands => 581,
            Country::Uruguay => 858,
            Country::Uzbekistan => 860,
            Country::Vanuatu => 548,
            Country::VenezuelaBolivarianRepublicof => 862,
            Country::VietNam => 704,
            Country::VirginIslandsBritish => 92,
            Country::VirginIslandsUS => 850,
            Country::WallisandFutuna => 876,
            Country::WesternSahara => 732,
            Country::Yemen => 887,
            Country::Zambia => 894,
            Country::Zimbabwe => 716,
        }
    }
}

mod custom_serde {
    use super::*;

    pub mod alpha2_country_code {
        use std::fmt;

        use serde::de::Visitor;

        use super::*;

        pub fn serialize<S>(code: &Country, serializer: S) -> Result<S::Ok, S::Error>
        where
            S: serde::Serializer,
        {
            code.to_alpha2().serialize(serializer)
        }

        struct FieldVisitor;

        impl<'de> Visitor<'de> for FieldVisitor {
            type Value = CountryAlpha2;

            fn expecting(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
                formatter.write_str("CountryAlpha2 as a string")
            }
        }

        pub fn deserialize<'a, D>(deserializer: D) -> Result<Country, D::Error>
        where
            D: serde::Deserializer<'a>,
        {
            CountryAlpha2::deserialize(deserializer).map(Country::from_alpha2)
        }
    }

    pub mod alpha3_country_code {
        use std::fmt;

        use serde::de::Visitor;

        use super::*;

        pub fn serialize<S>(code: &Country, serializer: S) -> Result<S::Ok, S::Error>
        where
            S: serde::Serializer,
        {
            code.to_alpha3().serialize(serializer)
        }

        struct FieldVisitor;

        impl<'de> Visitor<'de> for FieldVisitor {
            type Value = CountryAlpha3;

            fn expecting(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
                formatter.write_str("CountryAlpha3 as a string")
            }
        }

        pub fn deserialize<'a, D>(deserializer: D) -> Result<Country, D::Error>
        where
            D: serde::Deserializer<'a>,
        {
            CountryAlpha3::deserialize(deserializer).map(Country::from_alpha3)
        }
    }

    pub mod numeric_country_code {
        use std::fmt;

        use serde::de::Visitor;

        use super::*;

        pub fn serialize<S>(code: &Country, serializer: S) -> Result<S::Ok, S::Error>
        where
            S: serde::Serializer,
        {
            code.to_numeric().serialize(serializer)
        }

        struct FieldVisitor;

        impl<'de> Visitor<'de> for FieldVisitor {
            type Value = u32;

            fn expecting(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
                formatter.write_str("Numeric country code passed as an u32")
            }
        }

        pub fn deserialize<'a, D>(deserializer: D) -> Result<Country, D::Error>
        where
            D: serde::Deserializer<'a>,
        {
            u32::deserialize(deserializer).map(Country::from_numeric)
        }
    }
}

#[derive(Deserialize, Serialize)]
struct Address {
    #[serde(with = "custom_serde::alpha2_country_code")]
    country: Country,
}
#[derive(serde::Serialize)]
struct Alpha2Request {
    #[serde(with = "custom_serde::alpha2_country_code")]
    pub country: Country,
}

#[derive(serde::Serialize)]
struct Alpha3Request {
    #[serde(with = "custom_serde::alpha3_country_code")]
    pub country: Country,
}

#[derive(serde::Serialize)]
struct NumericRequest {
    #[serde(with = "custom_serde::numeric_country_code")]
    pub country: Country,
}

#[derive(serde::Serialize, serde::Deserialize)]
struct HyperswitchRequestAlpha2 {
    #[serde(with = "custom_serde::alpha2_country_code")]
    pub country: Country,
}

#[derive(serde::Serialize, serde::Deserialize)]
struct HyperswitchRequestAlpha3 {
    #[serde(with = "custom_serde::alpha3_country_code")]
    pub country: Country,
}

#[derive(serde::Serialize, serde::Deserialize)]
struct HyperswitchRequestNumeric {
    #[serde(with = "custom_serde::numeric_country_code")]
    pub country: Country,
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_serialize_alpha2() {
        let x_request = Alpha2Request {
            country: Country::India,
        };
        let serialized_country = serde_json::to_string(&x_request).unwrap();
        assert_eq!(serialized_country, r#"{"country":"IN"}"#);

        let x_request = Alpha2Request {
            country: Country::MacedoniatheformerYugoslavRepublicof,
        };
        let serialized_country = serde_json::to_string(&x_request).unwrap();
        assert_eq!(serialized_country, r#"{"country":"MK"}"#);

        let x_request = Alpha2Request {
            country: Country::FrenchSouthernTerritories,
        };
        let serialized_country = serde_json::to_string(&x_request).unwrap();
        assert_eq!(serialized_country, r#"{"country":"TF"}"#);
    }

    #[test]
    fn test_serialize_alpha3() {
        let y_request = Alpha3Request {
            country: Country::India,
        };
        let serialized_country = serde_json::to_string(&y_request).unwrap();
        assert_eq!(serialized_country, r#"{"country":"IND"}"#);

        let y_request = Alpha3Request {
            country: Country::HeardIslandandMcDonaldIslands,
        };
        let serialized_country = serde_json::to_string(&y_request).unwrap();
        assert_eq!(serialized_country, r#"{"country":"HMD"}"#);

        let y_request = Alpha3Request {
            country: Country::Argentina,
        };
        let serialized_country = serde_json::to_string(&y_request).unwrap();
        assert_eq!(serialized_country, r#"{"country":"ARG"}"#);
    }

    #[test]
    fn test_serialize_numeric() {
        let y_request = NumericRequest {
            country: Country::India,
        };
        let serialized_country = serde_json::to_string(&y_request).unwrap();
        assert_eq!(serialized_country, r#"{"country":356}"#);

        let y_request = NumericRequest {
            country: Country::Bermuda,
        };
        let serialized_country = serde_json::to_string(&y_request).unwrap();
        assert_eq!(serialized_country, r#"{"country":60}"#);

        let y_request = NumericRequest {
            country: Country::GuineaBissau,
        };
        let serialized_country = serde_json::to_string(&y_request).unwrap();
        assert_eq!(serialized_country, r#"{"country":624}"#);
    }

    #[test]
    fn test_deserialize_alpha2() {
        let request_str = r#"{"country":"IN"}"#;
        let request = serde_json::from_str::<HyperswitchRequestAlpha2>(request_str).unwrap();
        assert_eq!(request.country, Country::India);

        let request_str = r#"{"country":"GR"}"#;
        let request = serde_json::from_str::<HyperswitchRequestAlpha2>(request_str).unwrap();
        assert_eq!(request.country, Country::Greece);

        let request_str = r#"{"country":"IQ"}"#;
        let request = serde_json::from_str::<HyperswitchRequestAlpha2>(request_str).unwrap();
        assert_eq!(request.country, Country::Iraq);
    }

    #[test]
    fn test_deserialize_alpha3() {
        let request_str = r#"{"country":"IND"}"#;
        let request = serde_json::from_str::<HyperswitchRequestAlpha3>(request_str).unwrap();
        assert_eq!(request.country, Country::India);

        let request_str = r#"{"country":"LVA"}"#;
        let request = serde_json::from_str::<HyperswitchRequestAlpha3>(request_str).unwrap();
        assert_eq!(request.country, Country::Latvia);

        let request_str = r#"{"country":"PNG"}"#;
        let request = serde_json::from_str::<HyperswitchRequestAlpha3>(request_str).unwrap();
        assert_eq!(request.country, Country::PapuaNewGuinea);
    }

    #[test]
    fn test_deserialize_numeric() {
        let request_str = r#"{"country":356}"#;
        let request = serde_json::from_str::<HyperswitchRequestNumeric>(request_str).unwrap();
        assert_eq!(request.country, Country::India);

        let request_str = r#"{"country":239}"#;
        let request = serde_json::from_str::<HyperswitchRequestNumeric>(request_str).unwrap();
        assert_eq!(
            request.country,
            Country::SouthGeorgiaandtheSouthSandwichIslands
        );

        let request_str = r#"{"country":826}"#;
        let request = serde_json::from_str::<HyperswitchRequestNumeric>(request_str).unwrap();
        assert_eq!(
            request.country,
            Country::UnitedKingdomofGreatBritainandNorthernIreland
        );
    }

    #[test]
    fn test_deserialize_and_serialize() {
        // Deserialize the country as alpha2 code
        // Serialize the country as alpha3 code
        let request_str = r#"{"country":"IN"}"#;
        let request = serde_json::from_str::<HyperswitchRequestAlpha2>(request_str).unwrap();
        let alpha3_request = Alpha3Request {
            country: request.country,
        };
        let response = serde_json::to_string::<Alpha3Request>(&alpha3_request).unwrap();
        assert_eq!(response, r#"{"country":"IND"}"#)
    }

    #[test]
    fn test_serialize_and_deserialize() {
        let request_str = r#"{"country":"AX"}"#;
        let request = serde_json::from_str::<HyperswitchRequestAlpha2>(request_str).unwrap();
        let alpha3_request = Alpha3Request { country: request.country };
        let response = serde_json::to_string::<Alpha3Request>(&alpha3_request).unwrap();
        assert_eq!(response, r#"{"country":"ALA"}"#);

        let result = serde_json::from_str::<HyperswitchRequestAlpha3>(response.as_str()).unwrap();
        assert_eq!(result.country, Country::ÅlandIslands);
    }
}
