//! Data types and type conversions
//! from `redis`'s internal data-types to custom data-types

use common_utils::errors::CustomResult;
pub use redis::Value;
use redis::Value as RedisCrateValue;

use crate::{errors, RedisConnectionPool};

pub struct RedisValue {
    inner: RedisCrateValue,
}

impl std::ops::Deref for RedisValue {
    type Target = RedisCrateValue;

    fn deref(&self) -> &Self::Target {
        &self.inner
    }
}

impl RedisValue {
    pub fn new(value: RedisCrateValue) -> Self {
        Self { inner: value }
    }
    pub fn into_inner(self) -> RedisCrateValue {
        self.inner
    }

    pub fn from_bytes(val: Vec<u8>) -> Self {
        Self {
            inner: RedisCrateValue::BulkString(val),
        }
    }
    pub fn from_string(value: String) -> Self {
        Self {
            inner: RedisCrateValue::SimpleString(value),
        }
    }

    /// Extract bytes from the underlying redis value
    pub fn as_bytes(&self) -> Option<&[u8]> {
        match &self.inner {
            RedisCrateValue::BulkString(bytes) => Some(bytes.as_slice()),
            RedisCrateValue::SimpleString(s) => Some(s.as_bytes()),
            _ => None,
        }
    }

    /// Convert to string if the value is a string type
    pub fn as_string(&self) -> Option<String> {
        match &self.inner {
            RedisCrateValue::BulkString(bytes) => String::from_utf8(bytes.clone()).ok(),
            RedisCrateValue::SimpleString(s) => Some(s.clone()),
            _ => None,
        }
    }
}

impl From<RedisValue> for RedisCrateValue {
    fn from(v: RedisValue) -> Self {
        v.inner
    }
}

/// Allows conversion from RedisValue to bytes for use with ToRedisArgs
impl redis::ToRedisArgs for RedisValue {
    fn write_redis_args<W>(&self, out: &mut W)
    where
        W: ?Sized + redis::RedisWrite,
    {
        match &self.inner {
            RedisCrateValue::BulkString(bytes) => bytes.write_redis_args(out),
            RedisCrateValue::SimpleString(s) => s.write_redis_args(out),
            _ => {
                // Fallback: serialize as empty bytes
                Vec::<u8>::new().write_redis_args(out)
            }
        }
    }
}

impl redis::ToSingleRedisArg for RedisValue {}

#[derive(Debug, serde::Deserialize, Clone)]
#[serde(default)]
pub struct RedisSettings {
    pub host: String,
    pub port: u16,
    pub cluster_enabled: bool,
    pub cluster_urls: Vec<String>,
    pub use_legacy_version: bool,
    pub pool_size: usize,
    pub reconnect_max_attempts: u32,
    /// Reconnect delay in milliseconds
    pub reconnect_delay: u32,
    /// TTL in seconds
    pub default_ttl: u32,
    /// TTL for hash-tables in seconds
    pub default_hash_ttl: u32,
    pub stream_read_count: u64,
    pub auto_pipeline: bool,
    pub disable_auto_backpressure: bool,
    pub max_in_flight_commands: u64,
    pub default_command_timeout: u64,
    pub max_feed_count: u64,
    pub unresponsive_timeout: u64,
    pub unresponsive_check_interval: u64,
    pub broadcast_channel_capacity: usize,
}

impl RedisSettings {
    /// Validates the Redis configuration provided.
    pub fn validate(&self) -> CustomResult<(), errors::RedisError> {
        use common_utils::{ext_traits::ConfigExt, fp_utils::when};

        when(self.host.is_default_or_empty(), || {
            Err(errors::RedisError::InvalidConfiguration(
                "Redis `host` must be specified".into(),
            ))
        })?;

        when(self.cluster_enabled && self.cluster_urls.is_empty(), || {
            Err(errors::RedisError::InvalidConfiguration(
                "Redis `cluster_urls` must be specified if `cluster_enabled` is `true`".into(),
            ))
        })?;

        when(
            self.default_command_timeout < self.unresponsive_timeout,
            || {
                Err(errors::RedisError::InvalidConfiguration(
                    "Unresponsive timeout cannot be greater than the command timeout".into(),
                )
                .into())
            },
        )
    }
}

impl Default for RedisSettings {
    fn default() -> Self {
        Self {
            host: "127.0.0.1".to_string(),
            port: 6379,
            cluster_enabled: false,
            cluster_urls: vec![],
            use_legacy_version: false,
            pool_size: 5,
            reconnect_max_attempts: 5,
            reconnect_delay: 5,
            default_ttl: 300,
            stream_read_count: 1,
            default_hash_ttl: 900,
            auto_pipeline: true,
            disable_auto_backpressure: false,
            max_in_flight_commands: 5000,
            default_command_timeout: 30,
            max_feed_count: 200,
            unresponsive_timeout: 10,
            unresponsive_check_interval: 2,
            broadcast_channel_capacity: 32,
        }
    }
}

#[derive(Debug)]
pub enum RedisEntryId {
    UserSpecifiedID {
        milliseconds: String,
        sequence_number: String,
    },
    AutoGeneratedID,
    AfterLastID,
    /// Applicable only with consumer groups
    UndeliveredEntryID,
}

impl RedisEntryId {
    /// Convert to the string representation used by Redis stream commands
    pub fn to_stream_id(&self) -> String {
        match self {
            Self::UserSpecifiedID {
                milliseconds,
                sequence_number,
            } => format!("{milliseconds}-{sequence_number}"),
            Self::AutoGeneratedID => "*".to_string(),
            Self::AfterLastID => "$".to_string(),
            Self::UndeliveredEntryID => ">".to_string(),
        }
    }
}

impl redis::ToRedisArgs for RedisEntryId {
    fn write_redis_args<W>(&self, out: &mut W)
    where
        W: ?Sized + redis::RedisWrite,
    {
        self.to_stream_id().write_redis_args(out)
    }
}

#[derive(Debug, Eq, PartialEq)]
pub enum SetnxReply {
    KeySet,
    KeyNotSet, // Existing key
}

impl redis::FromRedisValue for SetnxReply {
    fn from_redis_value(v: Value) -> Result<Self, redis::ParsingError> {
        match v {
            // SET NX returns Okay on success (newer redis crate)
            Value::Okay => Ok(Self::KeySet),
            // SET NX returns "OK" on success (older format)
            Value::SimpleString(ref s) if s == "OK" => Ok(Self::KeySet),
            Value::BulkString(ref s) if s == b"OK" => Ok(Self::KeySet),
            // Returns Nil if key already exists
            Value::Nil => Ok(Self::KeyNotSet),
            _ => Err(redis::ParsingError::from(
                "Unexpected SETNX command reply".to_string(),
            )),
        }
    }
}

#[derive(Debug, Eq, PartialEq)]
pub enum HsetnxReply {
    KeySet,
    KeyNotSet, // Existing key
}

impl redis::FromRedisValue for HsetnxReply {
    fn from_redis_value(v: Value) -> Result<Self, redis::ParsingError> {
        match v {
            Value::Int(1) => Ok(Self::KeySet),
            Value::Int(0) => Ok(Self::KeyNotSet),
            _ => Err(redis::ParsingError::from(
                "Unexpected HSETNX command reply".to_string(),
            )),
        }
    }
}

#[derive(Debug, Eq, PartialEq)]
pub enum MsetnxReply {
    KeysSet,
    KeysNotSet, // At least one existing key
}

impl redis::FromRedisValue for MsetnxReply {
    fn from_redis_value(v: Value) -> Result<Self, redis::ParsingError> {
        match v {
            Value::Int(1) => Ok(Self::KeysSet),
            Value::Int(0) => Ok(Self::KeysNotSet),
            _ => Err(redis::ParsingError::from(
                "Unexpected MSETNX command reply".to_string(),
            )),
        }
    }
}

#[derive(Debug)]
pub enum StreamCapKind {
    MinID,
    MaxLen,
}

#[derive(Debug)]
pub enum StreamCapTrim {
    Exact,
    AlmostExact,
}

#[derive(Debug)]
pub enum DelReply {
    KeyDeleted,
    KeyNotDeleted, // Key not found
}

impl DelReply {
    pub fn is_key_deleted(&self) -> bool {
        matches!(self, Self::KeyDeleted)
    }

    pub fn is_key_not_deleted(&self) -> bool {
        matches!(self, Self::KeyNotDeleted)
    }
}

impl redis::FromRedisValue for DelReply {
    fn from_redis_value(v: Value) -> Result<Self, redis::ParsingError> {
        match v {
            Value::Int(1) => Ok(Self::KeyDeleted),
            Value::Int(0) => Ok(Self::KeyNotDeleted),
            _ => Err(redis::ParsingError::from(
                "Unexpected del command reply".to_string(),
            )),
        }
    }
}

#[derive(Debug)]
pub enum SaddReply {
    KeySet,
    KeyNotSet,
}

impl redis::FromRedisValue for SaddReply {
    fn from_redis_value(v: Value) -> Result<Self, redis::ParsingError> {
        match v {
            Value::Int(1) => Ok(Self::KeySet),
            Value::Int(0) => Ok(Self::KeyNotSet),
            _ => Err(redis::ParsingError::from(
                "Unexpected sadd command reply".to_string(),
            )),
        }
    }
}

#[derive(Debug)]
pub enum SetGetReply<T> {
    ValueSet(T),    // Value was set and this is the value that was set
    ValueExists(T), // Value already existed and this is the existing value
}

impl<T> SetGetReply<T> {
    pub fn get_value(&self) -> &T {
        match self {
            Self::ValueSet(value) => value,
            Self::ValueExists(value) => value,
        }
    }
}

#[derive(Debug)]
pub struct RedisKey(String);

impl RedisKey {
    pub fn tenant_aware_key(&self, pool: &RedisConnectionPool) -> String {
        pool.add_prefix(&self.0)
    }

    pub fn tenant_unaware_key(&self, _pool: &RedisConnectionPool) -> String {
        self.0.clone()
    }
}

impl<T: AsRef<str>> From<T> for RedisKey {
    fn from(value: T) -> Self {
        let value = value.as_ref();

        Self(value.to_string())
    }
}
