apiVersion: 1

datasources:
  - name: Traces
    type: tempo
    access: proxy
    url: http://tempo:3200/
    editable: true
    isDefault: false
  - name: Logs
    type: loki
    access: proxy
    url: http://loki:3100/
    editable: true
    isDefault: true
  - name: Metrics
    type: prometheus
    access: proxy
    url: http://prometheus:9090/
    editable: true
  - name: ClickHouse
    type: grafana-clickhouse-datasource
    jsonData:
      defaultDatabase: default
      port: 9000
      server: clickhouse-server
      username: default
      tlsSkipVerify: true
      protocol: native
    editable: true
  - name: PostgreSQL
    type: postgres
    access: proxy
    url: pg:5432
    database: hyperswitch_db
    user: db_user
    secureJsonData:
      password: db_pass
    jsonData:
      sslmode: disable
    editable: true
  - name: Redis
    type: redis-datasource
    access: proxy
    url: redis://redis-standalone:6379
    editable: true
