ALTER TABLE payment_attempt
ADD COLUMN IF NOT EXISTS network_advice_code VARCHAR(32) DEFAULT NULL,
ADD COLUMN IF NOT EXISTS network_decline_code VARCHAR(32) DEFAULT NULL,
ADD COLUMN IF NOT EXISTS network_error_message TEXT DEFAULT NULL;