# coding: utf-8

"""
    Hyperswitch - API Documentation

     ## Get started  Hyperswitch provides a collection of APIs that enable you to process and manage payments. Our APIs accept and return JSON in the HTTP body, and return standard HTTP response codes.  You can consume the APIs directly using your favorite HTTP/REST library.  We have a testing environment referred to \"sandbox\", which you can setup to test API calls without affecting production data. Currently, our sandbox environment is live while our production environment is under development and will be available soon. You can sign up on our Dashboard to get API keys to access Hyperswitch API.  ### Environment  Use the following base URLs when making requests to the APIs:  | Environment   |  Base URL                          | |---------------|------------------------------------| | Sandbox       | <https://sandbox.hyperswitch.io>   | | Production    | <https://api.hyperswitch.io>       |  ## Authentication  When you sign up on our [dashboard](https://app.hyperswitch.io) and create a merchant account, you are given a secret key (also referred as api-key) and a publishable key. You may authenticate all API requests with Hyperswitch server by providing the appropriate key in the request Authorization header.  | Key             |  Description                                                                                  | |-----------------|-----------------------------------------------------------------------------------------------| | api-key         | Private key. Used to authenticate all API requests from your merchant server                  | | publishable key | Unique identifier for your account. Used to authenticate API requests from your app's client  |  Never share your secret api keys. Keep them guarded and secure. 

    The version of the OpenAPI document: 0.1.0
    Contact: hyperswitch@juspay.in
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from hyperswitch.models.card_network import CardNetwork
from typing import Optional, Set
from typing_extensions import Self

class CardAdditionalData(BaseModel):
    """
    Masked payout method details for card payout method
    """ # noqa: E501
    card_issuer: Optional[StrictStr] = Field(default=None, description="Issuer of the card")
    card_network: Optional[CardNetwork] = None
    card_type: Optional[StrictStr] = Field(default=None, description="Card type, can be either `credit` or `debit`")
    card_issuing_country: Optional[StrictStr] = Field(default=None, description="Card issuing country")
    bank_code: Optional[StrictStr] = Field(default=None, description="Code for Card issuing bank")
    last4: Optional[StrictStr] = Field(default=None, description="Last 4 digits of the card number")
    card_isin: Optional[StrictStr] = Field(default=None, description="The ISIN of the card")
    card_extended_bin: Optional[StrictStr] = Field(default=None, description="Extended bin of card, contains the first 8 digits of card number")
    card_exp_month: StrictStr = Field(description="Card expiry month")
    card_exp_year: StrictStr = Field(description="Card expiry year")
    card_holder_name: StrictStr = Field(description="Card holder name")
    __properties: ClassVar[List[str]] = ["card_issuer", "card_network", "card_type", "card_issuing_country", "bank_code", "last4", "card_isin", "card_extended_bin", "card_exp_month", "card_exp_year", "card_holder_name"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CardAdditionalData from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if card_issuer (nullable) is None
        # and model_fields_set contains the field
        if self.card_issuer is None and "card_issuer" in self.model_fields_set:
            _dict['card_issuer'] = None

        # set to None if card_network (nullable) is None
        # and model_fields_set contains the field
        if self.card_network is None and "card_network" in self.model_fields_set:
            _dict['card_network'] = None

        # set to None if card_type (nullable) is None
        # and model_fields_set contains the field
        if self.card_type is None and "card_type" in self.model_fields_set:
            _dict['card_type'] = None

        # set to None if card_issuing_country (nullable) is None
        # and model_fields_set contains the field
        if self.card_issuing_country is None and "card_issuing_country" in self.model_fields_set:
            _dict['card_issuing_country'] = None

        # set to None if bank_code (nullable) is None
        # and model_fields_set contains the field
        if self.bank_code is None and "bank_code" in self.model_fields_set:
            _dict['bank_code'] = None

        # set to None if last4 (nullable) is None
        # and model_fields_set contains the field
        if self.last4 is None and "last4" in self.model_fields_set:
            _dict['last4'] = None

        # set to None if card_isin (nullable) is None
        # and model_fields_set contains the field
        if self.card_isin is None and "card_isin" in self.model_fields_set:
            _dict['card_isin'] = None

        # set to None if card_extended_bin (nullable) is None
        # and model_fields_set contains the field
        if self.card_extended_bin is None and "card_extended_bin" in self.model_fields_set:
            _dict['card_extended_bin'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CardAdditionalData from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "card_issuer": obj.get("card_issuer"),
            "card_network": obj.get("card_network"),
            "card_type": obj.get("card_type"),
            "card_issuing_country": obj.get("card_issuing_country"),
            "bank_code": obj.get("bank_code"),
            "last4": obj.get("last4"),
            "card_isin": obj.get("card_isin"),
            "card_extended_bin": obj.get("card_extended_bin"),
            "card_exp_month": obj.get("card_exp_month"),
            "card_exp_year": obj.get("card_exp_year"),
            "card_holder_name": obj.get("card_holder_name")
        })
        return _obj


