# coding: utf-8

"""
    Hyperswitch - API Documentation

     ## Get started  Hyperswitch provides a collection of APIs that enable you to process and manage payments. Our APIs accept and return JSON in the HTTP body, and return standard HTTP response codes.  You can consume the APIs directly using your favorite HTTP/REST library.  We have a testing environment referred to \"sandbox\", which you can setup to test API calls without affecting production data. Currently, our sandbox environment is live while our production environment is under development and will be available soon. You can sign up on our Dashboard to get API keys to access Hyperswitch API.  ### Environment  Use the following base URLs when making requests to the APIs:  | Environment   |  Base URL                          | |---------------|------------------------------------| | Sandbox       | <https://sandbox.hyperswitch.io>   | | Production    | <https://api.hyperswitch.io>       |  ## Authentication  When you sign up on our [dashboard](https://app.hyperswitch.io) and create a merchant account, you are given a secret key (also referred as api-key) and a publishable key. You may authenticate all API requests with Hyperswitch server by providing the appropriate key in the request Authorization header.  | Key             |  Description                                                                                  | |-----------------|-----------------------------------------------------------------------------------------------| | api-key         | Private key. Used to authenticate all API requests from your merchant server                  | | publishable key | Unique identifier for your account. Used to authenticate API requests from your app's client  |  Never share your secret api keys. Keep them guarded and secure. 

    The version of the OpenAPI document: 0.1.0
    Contact: hyperswitch@juspay.in
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict
from typing import Any, ClassVar, Dict, List, Optional
from hyperswitch.models.airwallex_data import AirwallexData
from hyperswitch.models.applepay_connector_metadata_request import ApplepayConnectorMetadataRequest
from hyperswitch.models.braintree_data import BraintreeData
from hyperswitch.models.noon_data import NoonData
from typing import Optional, Set
from typing_extensions import Self

class ConnectorMetadata(BaseModel):
    """
    Some connectors like Apple Pay, Airwallex and Noon might require some additional information, find specific details in the child attributes below.
    """ # noqa: E501
    apple_pay: Optional[ApplepayConnectorMetadataRequest] = None
    airwallex: Optional[AirwallexData] = None
    noon: Optional[NoonData] = None
    braintree: Optional[BraintreeData] = None
    __properties: ClassVar[List[str]] = ["apple_pay", "airwallex", "noon", "braintree"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ConnectorMetadata from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of apple_pay
        if self.apple_pay:
            _dict['apple_pay'] = self.apple_pay.to_dict()
        # override the default output from pydantic by calling `to_dict()` of airwallex
        if self.airwallex:
            _dict['airwallex'] = self.airwallex.to_dict()
        # override the default output from pydantic by calling `to_dict()` of noon
        if self.noon:
            _dict['noon'] = self.noon.to_dict()
        # override the default output from pydantic by calling `to_dict()` of braintree
        if self.braintree:
            _dict['braintree'] = self.braintree.to_dict()
        # set to None if apple_pay (nullable) is None
        # and model_fields_set contains the field
        if self.apple_pay is None and "apple_pay" in self.model_fields_set:
            _dict['apple_pay'] = None

        # set to None if airwallex (nullable) is None
        # and model_fields_set contains the field
        if self.airwallex is None and "airwallex" in self.model_fields_set:
            _dict['airwallex'] = None

        # set to None if noon (nullable) is None
        # and model_fields_set contains the field
        if self.noon is None and "noon" in self.model_fields_set:
            _dict['noon'] = None

        # set to None if braintree (nullable) is None
        # and model_fields_set contains the field
        if self.braintree is None and "braintree" in self.model_fields_set:
            _dict['braintree'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ConnectorMetadata from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "apple_pay": ApplepayConnectorMetadataRequest.from_dict(obj["apple_pay"]) if obj.get("apple_pay") is not None else None,
            "airwallex": AirwallexData.from_dict(obj["airwallex"]) if obj.get("airwallex") is not None else None,
            "noon": NoonData.from_dict(obj["noon"]) if obj.get("noon") is not None else None,
            "braintree": BraintreeData.from_dict(obj["braintree"]) if obj.get("braintree") is not None else None
        })
        return _obj


