# coding: utf-8

"""
    Hyperswitch - API Documentation

     ## Get started  Hyperswitch provides a collection of APIs that enable you to process and manage payments. Our APIs accept and return JSON in the HTTP body, and return standard HTTP response codes.  You can consume the APIs directly using your favorite HTTP/REST library.  We have a testing environment referred to \"sandbox\", which you can setup to test API calls without affecting production data. Currently, our sandbox environment is live while our production environment is under development and will be available soon. You can sign up on our Dashboard to get API keys to access Hyperswitch API.  ### Environment  Use the following base URLs when making requests to the APIs:  | Environment   |  Base URL                          | |---------------|------------------------------------| | Sandbox       | <https://sandbox.hyperswitch.io>   | | Production    | <https://api.hyperswitch.io>       |  ## Authentication  When you sign up on our [dashboard](https://app.hyperswitch.io) and create a merchant account, you are given a secret key (also referred as api-key) and a publishable key. You may authenticate all API requests with Hyperswitch server by providing the appropriate key in the request Authorization header.  | Key             |  Description                                                                                  | |-----------------|-----------------------------------------------------------------------------------------------| | api-key         | Private key. Used to authenticate all API requests from your merchant server                  | | publishable key | Unique identifier for your account. Used to authenticate API requests from your app's client  |  Never share your secret api keys. Keep them guarded and secure. 

    The version of the OpenAPI document: 0.1.0
    Contact: hyperswitch@juspay.in
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from hyperswitch.models.dispute_stage import DisputeStage
from hyperswitch.models.dispute_status import DisputeStatus
from typing import Optional, Set
from typing_extensions import Self

class DisputeResponsePaymentsRetrieve(BaseModel):
    """
    DisputeResponsePaymentsRetrieve
    """ # noqa: E501
    dispute_id: StrictStr = Field(description="The identifier for dispute")
    dispute_stage: DisputeStage
    dispute_status: DisputeStatus
    connector_status: StrictStr = Field(description="Status of the dispute sent by connector")
    connector_dispute_id: StrictStr = Field(description="Dispute id sent by connector")
    connector_reason: Optional[StrictStr] = Field(default=None, description="Reason of dispute sent by connector")
    connector_reason_code: Optional[StrictStr] = Field(default=None, description="Reason code of dispute sent by connector")
    challenge_required_by: Optional[datetime] = Field(default=None, description="Evidence deadline of dispute sent by connector")
    connector_created_at: Optional[datetime] = Field(default=None, description="Dispute created time sent by connector")
    connector_updated_at: Optional[datetime] = Field(default=None, description="Dispute updated time sent by connector")
    created_at: datetime = Field(description="Time at which dispute is received")
    __properties: ClassVar[List[str]] = ["dispute_id", "dispute_stage", "dispute_status", "connector_status", "connector_dispute_id", "connector_reason", "connector_reason_code", "challenge_required_by", "connector_created_at", "connector_updated_at", "created_at"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of DisputeResponsePaymentsRetrieve from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if connector_reason (nullable) is None
        # and model_fields_set contains the field
        if self.connector_reason is None and "connector_reason" in self.model_fields_set:
            _dict['connector_reason'] = None

        # set to None if connector_reason_code (nullable) is None
        # and model_fields_set contains the field
        if self.connector_reason_code is None and "connector_reason_code" in self.model_fields_set:
            _dict['connector_reason_code'] = None

        # set to None if challenge_required_by (nullable) is None
        # and model_fields_set contains the field
        if self.challenge_required_by is None and "challenge_required_by" in self.model_fields_set:
            _dict['challenge_required_by'] = None

        # set to None if connector_created_at (nullable) is None
        # and model_fields_set contains the field
        if self.connector_created_at is None and "connector_created_at" in self.model_fields_set:
            _dict['connector_created_at'] = None

        # set to None if connector_updated_at (nullable) is None
        # and model_fields_set contains the field
        if self.connector_updated_at is None and "connector_updated_at" in self.model_fields_set:
            _dict['connector_updated_at'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of DisputeResponsePaymentsRetrieve from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "dispute_id": obj.get("dispute_id"),
            "dispute_stage": obj.get("dispute_stage"),
            "dispute_status": obj.get("dispute_status"),
            "connector_status": obj.get("connector_status"),
            "connector_dispute_id": obj.get("connector_dispute_id"),
            "connector_reason": obj.get("connector_reason"),
            "connector_reason_code": obj.get("connector_reason_code"),
            "challenge_required_by": obj.get("challenge_required_by"),
            "connector_created_at": obj.get("connector_created_at"),
            "connector_updated_at": obj.get("connector_updated_at"),
            "created_at": obj.get("created_at")
        })
        return _obj


