# coding: utf-8

"""
    Hyperswitch - API Documentation

     ## Get started  Hyperswitch provides a collection of APIs that enable you to process and manage payments. Our APIs accept and return JSON in the HTTP body, and return standard HTTP response codes.  You can consume the APIs directly using your favorite HTTP/REST library.  We have a testing environment referred to \"sandbox\", which you can setup to test API calls without affecting production data. Currently, our sandbox environment is live while our production environment is under development and will be available soon. You can sign up on our Dashboard to get API keys to access Hyperswitch API.  ### Environment  Use the following base URLs when making requests to the APIs:  | Environment   |  Base URL                          | |---------------|------------------------------------| | Sandbox       | <https://sandbox.hyperswitch.io>   | | Production    | <https://api.hyperswitch.io>       |  ## Authentication  When you sign up on our [dashboard](https://app.hyperswitch.io) and create a merchant account, you are given a secret key (also referred as api-key) and a publishable key. You may authenticate all API requests with Hyperswitch server by providing the appropriate key in the request Authorization header.  | Key             |  Description                                                                                  | |-----------------|-----------------------------------------------------------------------------------------------| | api-key         | Private key. Used to authenticate all API requests from your merchant server                  | | publishable key | Unique identifier for your account. Used to authenticate API requests from your app's client  |  Never share your secret api keys. Keep them guarded and secure. 

    The version of the OpenAPI document: 0.1.0
    Contact: hyperswitch@juspay.in
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from hyperswitch.models.gpay_allowed_payment_methods import GpayAllowedPaymentMethods
from hyperswitch.models.gpay_merchant_info import GpayMerchantInfo
from hyperswitch.models.gpay_shipping_address_parameters import GpayShippingAddressParameters
from hyperswitch.models.gpay_transaction_info import GpayTransactionInfo
from hyperswitch.models.sdk_next_action import SdkNextAction
from hyperswitch.models.secret_info_to_initiate_sdk import SecretInfoToInitiateSdk
from typing import Optional, Set
from typing_extensions import Self

class GooglePaySessionResponse(BaseModel):
    """
    GooglePaySessionResponse
    """ # noqa: E501
    merchant_info: GpayMerchantInfo
    shipping_address_required: StrictBool = Field(description="Is shipping address required")
    email_required: StrictBool = Field(description="Is email required")
    shipping_address_parameters: GpayShippingAddressParameters
    allowed_payment_methods: List[GpayAllowedPaymentMethods] = Field(description="List of the allowed payment meythods")
    transaction_info: GpayTransactionInfo
    delayed_session_token: StrictBool = Field(description="Identifier for the delayed session response")
    connector: StrictStr = Field(description="The name of the connector")
    sdk_next_action: SdkNextAction
    secrets: Optional[SecretInfoToInitiateSdk] = None
    __properties: ClassVar[List[str]] = ["merchant_info", "shipping_address_required", "email_required", "shipping_address_parameters", "allowed_payment_methods", "transaction_info", "delayed_session_token", "connector", "sdk_next_action", "secrets"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of GooglePaySessionResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of merchant_info
        if self.merchant_info:
            _dict['merchant_info'] = self.merchant_info.to_dict()
        # override the default output from pydantic by calling `to_dict()` of shipping_address_parameters
        if self.shipping_address_parameters:
            _dict['shipping_address_parameters'] = self.shipping_address_parameters.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in allowed_payment_methods (list)
        _items = []
        if self.allowed_payment_methods:
            for _item_allowed_payment_methods in self.allowed_payment_methods:
                if _item_allowed_payment_methods:
                    _items.append(_item_allowed_payment_methods.to_dict())
            _dict['allowed_payment_methods'] = _items
        # override the default output from pydantic by calling `to_dict()` of transaction_info
        if self.transaction_info:
            _dict['transaction_info'] = self.transaction_info.to_dict()
        # override the default output from pydantic by calling `to_dict()` of sdk_next_action
        if self.sdk_next_action:
            _dict['sdk_next_action'] = self.sdk_next_action.to_dict()
        # override the default output from pydantic by calling `to_dict()` of secrets
        if self.secrets:
            _dict['secrets'] = self.secrets.to_dict()
        # set to None if secrets (nullable) is None
        # and model_fields_set contains the field
        if self.secrets is None and "secrets" in self.model_fields_set:
            _dict['secrets'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of GooglePaySessionResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "merchant_info": GpayMerchantInfo.from_dict(obj["merchant_info"]) if obj.get("merchant_info") is not None else None,
            "shipping_address_required": obj.get("shipping_address_required"),
            "email_required": obj.get("email_required"),
            "shipping_address_parameters": GpayShippingAddressParameters.from_dict(obj["shipping_address_parameters"]) if obj.get("shipping_address_parameters") is not None else None,
            "allowed_payment_methods": [GpayAllowedPaymentMethods.from_dict(_item) for _item in obj["allowed_payment_methods"]] if obj.get("allowed_payment_methods") is not None else None,
            "transaction_info": GpayTransactionInfo.from_dict(obj["transaction_info"]) if obj.get("transaction_info") is not None else None,
            "delayed_session_token": obj.get("delayed_session_token"),
            "connector": obj.get("connector"),
            "sdk_next_action": SdkNextAction.from_dict(obj["sdk_next_action"]) if obj.get("sdk_next_action") is not None else None,
            "secrets": SecretInfoToInitiateSdk.from_dict(obj["secrets"]) if obj.get("secrets") is not None else None
        })
        return _obj


