# coding: utf-8

"""
    Hyperswitch - API Documentation

     ## Get started  Hyperswitch provides a collection of APIs that enable you to process and manage payments. Our APIs accept and return JSON in the HTTP body, and return standard HTTP response codes.  You can consume the APIs directly using your favorite HTTP/REST library.  We have a testing environment referred to \"sandbox\", which you can setup to test API calls without affecting production data. Currently, our sandbox environment is live while our production environment is under development and will be available soon. You can sign up on our Dashboard to get API keys to access Hyperswitch API.  ### Environment  Use the following base URLs when making requests to the APIs:  | Environment   |  Base URL                          | |---------------|------------------------------------| | Sandbox       | <https://sandbox.hyperswitch.io>   | | Production    | <https://api.hyperswitch.io>       |  ## Authentication  When you sign up on our [dashboard](https://app.hyperswitch.io) and create a merchant account, you are given a secret key (also referred as api-key) and a publishable key. You may authenticate all API requests with Hyperswitch server by providing the appropriate key in the request Authorization header.  | Key             |  Description                                                                                  | |-----------------|-----------------------------------------------------------------------------------------------| | api-key         | Private key. Used to authenticate all API requests from your merchant server                  | | publishable key | Unique identifier for your account. Used to authenticate API requests from your app's client  |  Never share your secret api keys. Keep them guarded and secure. 

    The version of the OpenAPI document: 0.1.0
    Contact: hyperswitch@juspay.in
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class PaymentMethodType(str, Enum):
    """
    Indicates the sub type of payment method. Eg: 'google_pay' & 'apple_pay' for wallets.
    """

    """
    allowed enum values
    """
    ACH = 'ach'
    AFFIRM = 'affirm'
    AFTERPAY_CLEARPAY = 'afterpay_clearpay'
    ALFAMART = 'alfamart'
    ALI_PAY = 'ali_pay'
    ALI_PAY_HK = 'ali_pay_hk'
    ALMA = 'alma'
    AMAZON_PAY = 'amazon_pay'
    APPLE_PAY = 'apple_pay'
    ATOME = 'atome'
    BACS = 'bacs'
    BANCONTACT_CARD = 'bancontact_card'
    BECS = 'becs'
    BENEFIT = 'benefit'
    BIZUM = 'bizum'
    BLIK = 'blik'
    BOLETO = 'boleto'
    BCA_BANK_TRANSFER = 'bca_bank_transfer'
    BNI_VA = 'bni_va'
    BRI_VA = 'bri_va'
    CARD_REDIRECT = 'card_redirect'
    CIMB_VA = 'cimb_va'
    CLASSIC = 'classic'
    CREDIT = 'credit'
    CRYPTO_CURRENCY = 'crypto_currency'
    CASHAPP = 'cashapp'
    DANA = 'dana'
    DANAMON_VA = 'danamon_va'
    DEBIT = 'debit'
    DUIT_NOW = 'duit_now'
    EFECTY = 'efecty'
    EFT = 'eft'
    EPS = 'eps'
    FPS = 'fps'
    EVOUCHER = 'evoucher'
    GIROPAY = 'giropay'
    GIVEX = 'givex'
    GOOGLE_PAY = 'google_pay'
    GO_PAY = 'go_pay'
    GCASH = 'gcash'
    IDEAL = 'ideal'
    INTERAC = 'interac'
    INDOMARET = 'indomaret'
    KLARNA = 'klarna'
    KAKAO_PAY = 'kakao_pay'
    LOCAL_BANK_REDIRECT = 'local_bank_redirect'
    MANDIRI_VA = 'mandiri_va'
    KNET = 'knet'
    MB_WAY = 'mb_way'
    MOBILE_PAY = 'mobile_pay'
    MOMO = 'momo'
    MOMO_ATM = 'momo_atm'
    MULTIBANCO = 'multibanco'
    ONLINE_BANKING_THAILAND = 'online_banking_thailand'
    ONLINE_BANKING_CZECH_REPUBLIC = 'online_banking_czech_republic'
    ONLINE_BANKING_FINLAND = 'online_banking_finland'
    ONLINE_BANKING_FPX = 'online_banking_fpx'
    ONLINE_BANKING_POLAND = 'online_banking_poland'
    ONLINE_BANKING_SLOVAKIA = 'online_banking_slovakia'
    OXXO = 'oxxo'
    PAGO_EFECTIVO = 'pago_efectivo'
    PERMATA_BANK_TRANSFER = 'permata_bank_transfer'
    OPEN_BANKING_UK = 'open_banking_uk'
    PAY_BRIGHT = 'pay_bright'
    PAYPAL = 'paypal'
    PAZE = 'paze'
    PIX = 'pix'
    PAY_SAFE_CARD = 'pay_safe_card'
    PRZELEWY24 = 'przelewy24'
    PROMPT_PAY = 'prompt_pay'
    PSE = 'pse'
    RED_COMPRA = 'red_compra'
    RED_PAGOS = 'red_pagos'
    SAMSUNG_PAY = 'samsung_pay'
    SEPA = 'sepa'
    SEPA_BANK_TRANSFER = 'sepa_bank_transfer'
    SOFORT = 'sofort'
    SWISH = 'swish'
    TOUCH_N_GO = 'touch_n_go'
    TRUSTLY = 'trustly'
    TWINT = 'twint'
    UPI_COLLECT = 'upi_collect'
    UPI_INTENT = 'upi_intent'
    VIPPS = 'vipps'
    VIET_QR = 'viet_qr'
    VENMO = 'venmo'
    WALLEY = 'walley'
    WE_CHAT_PAY = 'we_chat_pay'
    SEVEN_ELEVEN = 'seven_eleven'
    LAWSON = 'lawson'
    MINI_STOP = 'mini_stop'
    FAMILY_MART = 'family_mart'
    SEICOMART = 'seicomart'
    PAY_EASY = 'pay_easy'
    LOCAL_BANK_TRANSFER = 'local_bank_transfer'
    MIFINITY = 'mifinity'
    OPEN_BANKING_PIS = 'open_banking_pis'
    DIRECT_CARRIER_BILLING = 'direct_carrier_billing'
    INSTANT_BANK_TRANSFER = 'instant_bank_transfer'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of PaymentMethodType from a JSON string"""
        return cls(json.loads(json_str))


