# coding: utf-8

"""
    Hyperswitch - API Documentation

     ## Get started  Hyperswitch provides a collection of APIs that enable you to process and manage payments. Our APIs accept and return JSON in the HTTP body, and return standard HTTP response codes.  You can consume the APIs directly using your favorite HTTP/REST library.  We have a testing environment referred to \"sandbox\", which you can setup to test API calls without affecting production data. Currently, our sandbox environment is live while our production environment is under development and will be available soon. You can sign up on our Dashboard to get API keys to access Hyperswitch API.  ### Environment  Use the following base URLs when making requests to the APIs:  | Environment   |  Base URL                          | |---------------|------------------------------------| | Sandbox       | <https://sandbox.hyperswitch.io>   | | Production    | <https://api.hyperswitch.io>       |  ## Authentication  When you sign up on our [dashboard](https://app.hyperswitch.io) and create a merchant account, you are given a secret key (also referred as api-key) and a publishable key. You may authenticate all API requests with Hyperswitch server by providing the appropriate key in the request Authorization header.  | Key             |  Description                                                                                  | |-----------------|-----------------------------------------------------------------------------------------------| | api-key         | Private key. Used to authenticate all API requests from your merchant server                  | | publishable key | Unique identifier for your account. Used to authenticate API requests from your app's client  |  Never share your secret api keys. Keep them guarded and secure. 

    The version of the OpenAPI document: 0.1.0
    Contact: hyperswitch@juspay.in
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from hyperswitch.models.currency import Currency
from hyperswitch.models.payment_link_status import PaymentLinkStatus
from typing import Optional, Set
from typing_extensions import Self

class RetrievePaymentLinkResponse(BaseModel):
    """
    RetrievePaymentLinkResponse
    """ # noqa: E501
    payment_link_id: StrictStr = Field(description="Identifier for Payment Link")
    merchant_id: StrictStr = Field(description="Identifier for Merchant")
    link_to_pay: StrictStr = Field(description="Open payment link (without any security checks and listing SPMs)")
    amount: StrictInt = Field(description="The payment amount. Amount for the payment in the lowest denomination of the currency")
    created_at: datetime = Field(description="Date and time of Payment Link creation")
    expiry: Optional[datetime] = Field(default=None, description="Date and time of Expiration for Payment Link")
    description: Optional[StrictStr] = Field(default=None, description="Description for Payment Link")
    status: PaymentLinkStatus
    currency: Optional[Currency] = None
    secure_link: Optional[StrictStr] = Field(default=None, description="Secure payment link (with security checks and listing saved payment methods)")
    __properties: ClassVar[List[str]] = ["payment_link_id", "merchant_id", "link_to_pay", "amount", "created_at", "expiry", "description", "status", "currency", "secure_link"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of RetrievePaymentLinkResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if expiry (nullable) is None
        # and model_fields_set contains the field
        if self.expiry is None and "expiry" in self.model_fields_set:
            _dict['expiry'] = None

        # set to None if description (nullable) is None
        # and model_fields_set contains the field
        if self.description is None and "description" in self.model_fields_set:
            _dict['description'] = None

        # set to None if currency (nullable) is None
        # and model_fields_set contains the field
        if self.currency is None and "currency" in self.model_fields_set:
            _dict['currency'] = None

        # set to None if secure_link (nullable) is None
        # and model_fields_set contains the field
        if self.secure_link is None and "secure_link" in self.model_fields_set:
            _dict['secure_link'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of RetrievePaymentLinkResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "payment_link_id": obj.get("payment_link_id"),
            "merchant_id": obj.get("merchant_id"),
            "link_to_pay": obj.get("link_to_pay"),
            "amount": obj.get("amount"),
            "created_at": obj.get("created_at"),
            "expiry": obj.get("expiry"),
            "description": obj.get("description"),
            "status": obj.get("status"),
            "currency": obj.get("currency"),
            "secure_link": obj.get("secure_link")
        })
        return _obj


