# coding: utf-8

"""
    Hyperswitch - API Documentation

     ## Get started  Hyperswitch provides a collection of APIs that enable you to process and manage payments. Our APIs accept and return JSON in the HTTP body, and return standard HTTP response codes.  You can consume the APIs directly using your favorite HTTP/REST library.  We have a testing environment referred to \"sandbox\", which you can setup to test API calls without affecting production data. Currently, our sandbox environment is live while our production environment is under development and will be available soon. You can sign up on our Dashboard to get API keys to access Hyperswitch API.  ### Environment  Use the following base URLs when making requests to the APIs:  | Environment   |  Base URL                          | |---------------|------------------------------------| | Sandbox       | <https://sandbox.hyperswitch.io>   | | Production    | <https://api.hyperswitch.io>       |  ## Authentication  When you sign up on our [dashboard](https://app.hyperswitch.io) and create a merchant account, you are given a secret key (also referred as api-key) and a publishable key. You may authenticate all API requests with Hyperswitch server by providing the appropriate key in the request Authorization header.  | Key             |  Description                                                                                  | |-----------------|-----------------------------------------------------------------------------------------------| | api-key         | Private key. Used to authenticate all API requests from your merchant server                  | | publishable key | Unique identifier for your account. Used to authenticate API requests from your app's client  |  Never share your secret api keys. Keep them guarded and secure. 

    The version of the OpenAPI document: 0.1.0
    Contact: hyperswitch@juspay.in
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing_extensions import Annotated
from hyperswitch.models.current_block_threshold import CurrentBlockThreshold
from hyperswitch.models.success_rate_specificity_level import SuccessRateSpecificityLevel
from typing import Optional, Set
from typing_extensions import Self

class SuccessBasedRoutingConfigBody(BaseModel):
    """
    SuccessBasedRoutingConfigBody
    """ # noqa: E501
    min_aggregates_size: Optional[Annotated[int, Field(strict=True, ge=0)]] = None
    default_success_rate: Optional[Union[StrictFloat, StrictInt]] = None
    max_aggregates_size: Optional[Annotated[int, Field(strict=True, ge=0)]] = None
    current_block_threshold: Optional[CurrentBlockThreshold] = None
    specificity_level: Optional[SuccessRateSpecificityLevel] = None
    __properties: ClassVar[List[str]] = ["min_aggregates_size", "default_success_rate", "max_aggregates_size", "current_block_threshold", "specificity_level"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of SuccessBasedRoutingConfigBody from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of current_block_threshold
        if self.current_block_threshold:
            _dict['current_block_threshold'] = self.current_block_threshold.to_dict()
        # set to None if min_aggregates_size (nullable) is None
        # and model_fields_set contains the field
        if self.min_aggregates_size is None and "min_aggregates_size" in self.model_fields_set:
            _dict['min_aggregates_size'] = None

        # set to None if default_success_rate (nullable) is None
        # and model_fields_set contains the field
        if self.default_success_rate is None and "default_success_rate" in self.model_fields_set:
            _dict['default_success_rate'] = None

        # set to None if max_aggregates_size (nullable) is None
        # and model_fields_set contains the field
        if self.max_aggregates_size is None and "max_aggregates_size" in self.model_fields_set:
            _dict['max_aggregates_size'] = None

        # set to None if current_block_threshold (nullable) is None
        # and model_fields_set contains the field
        if self.current_block_threshold is None and "current_block_threshold" in self.model_fields_set:
            _dict['current_block_threshold'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of SuccessBasedRoutingConfigBody from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "min_aggregates_size": obj.get("min_aggregates_size"),
            "default_success_rate": obj.get("default_success_rate"),
            "max_aggregates_size": obj.get("max_aggregates_size"),
            "current_block_threshold": CurrentBlockThreshold.from_dict(obj["current_block_threshold"]) if obj.get("current_block_threshold") is not None else None,
            "specificity_level": obj.get("specificity_level")
        })
        return _obj


