/*
 * Hyperswitch - API Documentation
 *
 *  ## Get started  Hyperswitch provides a collection of APIs that enable you to process and manage payments. Our APIs accept and return JSON in the HTTP body, and return standard HTTP response codes.  You can consume the APIs directly using your favorite HTTP/REST library.  We have a testing environment referred to \"sandbox\", which you can setup to test API calls without affecting production data. Currently, our sandbox environment is live while our production environment is under development and will be available soon. You can sign up on our Dashboard to get API keys to access Hyperswitch API.  ### Environment  Use the following base URLs when making requests to the APIs:  | Environment   |  Base URL                          | |---------------|------------------------------------| | Sandbox       | <https://sandbox.hyperswitch.io>   | | Production    | <https://api.hyperswitch.io>       |  ## Authentication  When you sign up on our [dashboard](https://app.hyperswitch.io) and create a merchant account, you are given a secret key (also referred as api-key) and a publishable key. You may authenticate all API requests with Hyperswitch server by providing the appropriate key in the request Authorization header.  | Key             |  Description                                                                                  | |-----------------|-----------------------------------------------------------------------------------------------| | api-key         | Private key. Used to authenticate all API requests from your merchant server                  | | publishable key | Unique identifier for your account. Used to authenticate API requests from your app's client  |  Never share your secret api keys. Keep them guarded and secure. 
 *
 * The version of the OpenAPI document: 0.2.0
 * Contact: hyperswitch@juspay.in
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct CardDetailFromLocker {
    #[serde(rename = "scheme", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub scheme: Option<Option<String>>,
    #[serde(rename = "issuer_country", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub issuer_country: Option<Option<String>>,
    #[serde(rename = "last4_digits", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub last4_digits: Option<Option<String>>,
    #[serde(rename = "expiry_month", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub expiry_month: Option<Option<String>>,
    #[serde(rename = "expiry_year", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub expiry_year: Option<Option<String>>,
    #[serde(rename = "card_token", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub card_token: Option<Option<String>>,
    #[serde(rename = "card_holder_name", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub card_holder_name: Option<Option<String>>,
    #[serde(rename = "card_fingerprint", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub card_fingerprint: Option<Option<String>>,
    #[serde(rename = "nick_name", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub nick_name: Option<Option<String>>,
}

impl CardDetailFromLocker {
    pub fn new() -> CardDetailFromLocker {
        CardDetailFromLocker {
            scheme: None,
            issuer_country: None,
            last4_digits: None,
            expiry_month: None,
            expiry_year: None,
            card_token: None,
            card_holder_name: None,
            card_fingerprint: None,
            nick_name: None,
        }
    }
}


