/*
 * Hyperswitch - API Documentation
 *
 *  ## Get started  Hyperswitch provides a collection of APIs that enable you to process and manage payments. Our APIs accept and return JSON in the HTTP body, and return standard HTTP response codes.  You can consume the APIs directly using your favorite HTTP/REST library.  We have a testing environment referred to \"sandbox\", which you can setup to test API calls without affecting production data. Currently, our sandbox environment is live while our production environment is under development and will be available soon. You can sign up on our Dashboard to get API keys to access Hyperswitch API.  ### Environment  Use the following base URLs when making requests to the APIs:  | Environment   |  Base URL                          | |---------------|------------------------------------| | Sandbox       | <https://sandbox.hyperswitch.io>   | | Production    | <https://api.hyperswitch.io>       |  ## Authentication  When you sign up on our [dashboard](https://app.hyperswitch.io) and create a merchant account, you are given a secret key (also referred as api-key) and a publishable key. You may authenticate all API requests with Hyperswitch server by providing the appropriate key in the request Authorization header.  | Key             |  Description                                                                                  | |-----------------|-----------------------------------------------------------------------------------------------| | api-key         | Private key. Used to authenticate all API requests from your merchant server                  | | publishable key | Unique identifier for your account. Used to authenticate API requests from your app's client  |  Never share your secret api keys. Keep them guarded and secure. 
 *
 * The version of the OpenAPI document: 0.2.0
 * Contact: hyperswitch@juspay.in
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct Card {
    /// The card number
    #[serde(rename = "card_number")]
    pub card_number: String,
    /// The card's expiry month
    #[serde(rename = "card_exp_month")]
    pub card_exp_month: String,
    /// The card's expiry year
    #[serde(rename = "card_exp_year")]
    pub card_exp_year: String,
    /// The card holder's name
    #[serde(rename = "card_holder_name")]
    pub card_holder_name: String,
    /// The CVC number for the card
    #[serde(rename = "card_cvc")]
    pub card_cvc: String,
    /// The name of the issuer of card
    #[serde(rename = "card_issuer", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub card_issuer: Option<Option<String>>,
    #[serde(rename = "card_network", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub card_network: Option<Option<crate::models::CardNetwork>>,
    #[serde(rename = "card_type", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub card_type: Option<Option<String>>,
    #[serde(rename = "card_issuing_country", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub card_issuing_country: Option<Option<String>>,
    #[serde(rename = "bank_code", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub bank_code: Option<Option<String>>,
    /// The card holder's nick name
    #[serde(rename = "nick_name", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub nick_name: Option<Option<String>>,
}

impl Card {
    pub fn new(card_number: String, card_exp_month: String, card_exp_year: String, card_holder_name: String, card_cvc: String) -> Card {
        Card {
            card_number,
            card_exp_month,
            card_exp_year,
            card_holder_name,
            card_cvc,
            card_issuer: None,
            card_network: None,
            card_type: None,
            card_issuing_country: None,
            bank_code: None,
            nick_name: None,
        }
    }
}


